
import { MenuItem } from './types';

export const EQUIPMENT_LIST = [
  "水轮机", "发电机", "输电装置", "泵站", "排污口检测", 
  "污水处理", "风机电组", "船舶", "靠泊系统", "起重设备", 
  "航标", "测速仪", "矿山提升机", "掘进设备", "钻孔设备", 
  "破碎设备", "选矿设备", "制砂机"
];

// Generate children items for the Smart Ops menu
const SMART_OPS_CHILDREN: MenuItem[] = EQUIPMENT_LIST.map((name, index) => ({
  id: `eq-${index}`,
  label: `${name}智能运维`
}));

// Knowledge Base Children
const PRODUCT_KB_CHILDREN: MenuItem[] = [
  { id: 'kb-ship-power', label: '船舶动力部件知识库' },
  { id: 'kb-channel-equip', label: '航道设备组件知识库' },
  { id: 'kb-port-machinery', label: '港口机械部件知识库' },
  { id: 'kb-port-channel-sys', label: '港口与航道系统知识库' },
  { id: 'kb-ship-lock', label: '船闸运行工况知识库' },
  { id: 'kb-dispatch-rules', label: '航道通航调度规则' },
  { id: 'kb-ship-adapt', label: '船型与航道适配规则' },
  { id: 'kb-port-combo', label: '港口装备组合方案库' },
  { id: 'kb-mining-equip', label: '采掘设备知识库' },
  { id: 'kb-transport-equip', label: '运输设备知识库' },
  { id: 'kb-crushing-equip', label: '破碎与分选设备知识库' },
  { id: 'kb-hydro-gen', label: '水轮发电机组知识库' },
  { id: 'kb-pumped-storage', label: '抽水蓄能机组知识库' },
  { id: 'kb-hydro-aux', label: '水电站辅助系统知识库' },
  { id: 'kb-water-conveyance', label: '输水系统知识库' },
];

// Cockpit Children
const COCKPIT_CHILDREN: MenuItem[] = [
  { id: 'cp-mining-dispatch', label: '露天矿车智能调度驾驶舱' },
  { id: 'cp-mining-safety', label: '井下六大系统安全态势驾驶舱' },
  { id: 'cp-tailings-safety', label: '矿库安全监测预警驾驶舱' },
  { id: 'cp-mining-eco', label: '矿山生态修复与环保驾驶舱' },
  { id: 'cp-mining-emergency', label: '矿山应急救援指挥驾驶舱' },
  { id: 'cp-hydro-cascade', label: '流域梯级电站联合调度驾驶舱' },
  { id: 'cp-dam-safety', label: '大坝安全与水工建筑驾驶舱' },
  { id: 'cp-flood-control', label: '防洪度汛与水情测报驾驶舱' },
  { id: 'cp-pumped-storage', label: '抽水蓄能电站运行驾驶舱' },
  { id: 'cp-smart-water', label: '城市智慧水务全网驾驶舱' },
  { id: 'cp-irrigation', label: '大型灌区水资源配置驾驶舱' },
  { id: 'cp-ocean-fleet', label: '全球远洋船队监控驾驶舱' },
  { id: 'cp-container-terminal', label: '集装箱码头生产作业驾驶舱' },
  { id: 'cp-bulk-terminal', label: '散货码头物流驾驶舱' },
  { id: 'cp-inland-waterway', label: '内河航道与通航枢纽驾驶舱' },
  { id: 'cp-green-port', label: '绿色港口能耗与碳排驾驶舱' },
  { id: 'cp-maritime-safety', label: '水上交通安全监管驾驶舱' },

];

// Index Analysis Children
const INDEX_ANALYSIS_CHILDREN: MenuItem[] = [
  { id: 'ia-mining-recovery', label: '采矿回采率与贫化率分析' },
  { id: 'ia-mineral-recovery', label: '选矿金属回收率分析' },
  { id: 'ia-mining-oee', label: '综采设备OEE（设备综合效率）分析' },
  { id: 'ia-truck-cycle', label: '矿用卡车运循环效能分析' },
  { id: 'ia-blasting-quality', label: '爆破效果质量指数分析' },
  { id: 'ia-mining-energy', label: '矿山能耗单耗分析' },
  { id: 'ia-ventilation', label: '通风系统风量有效率分析' },
  { id: 'ia-hydro-util', label: '水能利用率与耗水率分析' },
  { id: 'ia-spillage-loss', label: '机组弃水损失电量分析' },
  { id: 'ia-turbine-wear', label: '水轮机气蚀与磨损指数分析' },
  { id: 'ia-reservoir-benefit', label: '水库兴利调度效益分析' },
  { id: 'ia-dam-health', label: '大坝安全综合健康指数' },
  { id: 'ia-ps-efficiency', label: '抽水蓄能综合转换效率分析' },
  { id: 'ia-power-ram', label: '发电设备可靠性指标(RAM)分析' },
  { id: 'ia-berth-util', label: '港口泊位利用率与周转率分析' },
  { id: 'ia-crane-efficiency', label: '岸桥/场桥作业效率(MPH)分析' },
  { id: 'ia-ship-eeoi', label: '船舶能效营运指数(EEOI)分析' },
  { id: 'ia-ship-cii', label: '船舶碳强度指标(CII)评级分析' },
  { id: 'ia-lock-efficiency', label: '闸坝通航效率指数分析' },
  { id: 'ia-transport-connect', label: '集疏运体系衔接效率分析' },
  { id: 'ia-channel-safety', label: '航道通航安全风险指数' },
];

// Digital Delivery Children
const DIGITAL_DELIVERY_CHILDREN: MenuItem[] = [
  { id: 'dd-hydro-completion', label: '水利水电工程竣工数字化交付' },
  { id: 'dd-hydro-twin', label: '数字孪生水电站交付' },
  { id: 'dd-hydro-bim', label: '水工建筑物BIM模型交付' },
  { id: 'dd-hydro-dispatch', label: '水库调度模型与规则数字交付' },
  { id: 'dd-hydro-equip-lifecycle', label: '机组设备全生命周期数据交付' },
  { id: 'dd-dam-safety', label: '大坝安全监测系统数字交付' },
  { id: 'dd-hydro-monitor', label: '水文监测与预报模型交付' },
  { id: 'dd-flood-control', label: '防洪调度与应急推演系统交付' },
  { id: 'dd-hydro-asset', label: '水电站资产与运维台账数字交付' },
  { id: 'dd-mine-construction', label: '数字矿山整体建设交付' },
  { id: 'dd-mine-bim', label: '矿山BIM/GIM一体化模型交付' },
  { id: 'dd-mine-process', label: '采掘工艺与流程数字化移交' },
  { id: 'dd-mine-processing', label: '智能选矿与洗选系统数字交付' },
  { id: 'dd-mine-equip-lifecycle', label: '矿山设备全生命周期档案交付' },
  { id: 'dd-mine-safety', label: '安全生产监测预警系统交付' },
  { id: 'dd-mine-geo', label: '地质建模与资源储量模型交付' },
  { id: 'dd-mine-transport', label: '运输与提升系统数字化交付' },
  { id: 'dd-mine-energy', label: '能耗与碳排放监测系统交付' },
  { id: 'dd-mine-eco', label: '矿山生态修复与闭坑数字交付' },
  { id: 'dd-port-completion', label: '港口工程竣工数字化交付' },
  { id: 'dd-port-bim', label: '港航设施BIM模型数字交付' },
  { id: 'dd-channel-regulation', label: '航道整治工程数字移交' },
  { id: 'dd-ship-lock', label: '船闸枢纽数字化交付' },
  { id: 'dd-smart-port', label: '智慧港口管理系统交付' },
  { id: 'dd-nav-dispatch', label: '通航调度与指挥系统交付' },
  { id: 'dd-ship-lifecycle', label: '船舶全生命周期数字交付' },
  { id: 'dd-port-asset', label: '港口设备设施资产数字交付' },
  { id: 'dd-channel-monitor', label: '航道监测与维护系统交付' },
  { id: 'dd-nav-safety', label: '应急通航与安全管理系统交付' },
];

// Simulation Children (NEW)
export const SIMULATION_CHILDREN: MenuItem[] = [
    // Mining
    { id: 'sim-mine-vent', label: '井下通风与有害气体扩散仿真' },
    { id: 'sim-mine-roof', label: '采掘工作面顶板稳定性仿真' },
    { id: 'sim-mine-blast', label: '爆破震动与冲击波传播仿真' },
    { id: 'sim-mine-truck', label: '矿山卡车运输路径与拥堵仿真' },
    { id: 'sim-mine-slope', label: '露天矿边坡稳定性仿真' },
    { id: 'sim-mine-equip', label: '采矿设备结构强度与疲劳寿命仿真' },
    { id: 'sim-mine-belt', label: '皮带输送系统动态仿真' },
    { id: 'sim-mine-evac', label: '井下行人安全疏散路径仿真' },
    { id: 'sim-mine-water', label: '矿井水害涌水与排水系统仿真' },
    { id: 'sim-mine-power', label: '矿山电力系统负荷与故障仿真' },
    { id: 'sim-mine-coop', label: '自卸卡车-装载机协同作业效率仿真' },
    { id: 'sim-mine-hoist', label: '矿用提升机运行与钢丝绳受力仿真' },
    { id: 'sim-mine-dust', label: '粉尘源产生与除尘系统效率仿真' },
    { id: 'sim-mine-freeze', label: '矿山井筒冻结法施工温度场仿真' },
    { id: 'sim-mine-crash', label: '矿车碰撞与防撞缓冲结构仿真' },
    { id: 'sim-mine-slurry', label: '选矿流程中矿浆流动与分级效率仿真' },
    { id: 'sim-mine-dispatch', label: '矿山智能调度系统“人-车-设备”联合仿真' },
    { id: 'sim-mine-eco', label: '矿区生态修复与地表形态演化仿真' },
    // Hydro
    { id: 'sim-hydro-flood', label: '水库调度与洪水演进过程仿真' },
    { id: 'sim-hydro-spill', label: '溢洪道泄流能力与消能工水力仿真' },
    { id: 'sim-hydro-dam', label: '大坝坝体应力-渗流-温度耦合仿真' },
    { id: 'sim-hydro-gate', label: '闸门启闭过程流固耦合仿真' },
    { id: 'sim-hydro-turb', label: '水电站机组（蜗壳-导叶-转轮）水力性能仿真' },
    { id: 'sim-hydro-river', label: '河道整治工程中河床冲淤演变仿真' },
    { id: 'sim-hydro-urban', label: '城市内涝积水与排水管网运行仿真' },
    { id: 'sim-hydro-sedi', label: '水库泥沙淤积与调沙方案仿真' },
    { id: 'sim-hydro-break', label: '堤防漫顶溃口演化与淹没范围仿真' },
    { id: 'sim-hydro-trans', label: '水电机组启停过渡过程电-机-水联合仿真' },
    { id: 'sim-hydro-group', label: '水闸群联合调度与上下游水位协同仿真' },
    { id: 'sim-hydro-pump', label: '泵站运行工况与能耗优化仿真' },
    { id: 'sim-hydro-fish', label: '生态下泄流量与鱼道通行仿真' },
    { id: 'sim-hydro-grid', label: '水库-电网联合调度（流量-发电-负荷）仿真' },
    { id: 'sim-hydro-emer', label: '高坝溃坝极端工况应急演练仿真' },
    { id: 'sim-hydro-ice', label: '冰情（凌汛）对河道行洪能力影响仿真' },
    { id: 'sim-hydro-vib', label: '水工建筑物振动与动荷载响应仿真' },
    // Port/Nav
    { id: 'sim-port-flow', label: '船舶在港航道交通流仿真' },
    { id: 'sim-port-lock', label: '船闸过闸调度与船舶排队仿真' },
    { id: 'sim-port-motion', label: '复杂海况/内河工况下船舶运动仿真' },
    { id: 'sim-port-load', label: '码头装卸作业与岸桥调度仿真' },
    { id: 'sim-port-multi', label: '港区集疏运（公路+铁路）多式联运仿真' },
    { id: 'sim-port-reg', label: '航道整治工程对通航条件的影响仿真' },
    { id: 'sim-port-coll', label: '船舶碰撞与搁浅事故仿真' },
    { id: 'sim-port-spill', label: '港区油品/危险品泄漏扩散仿真' },
    { id: 'sim-port-berth', label: '船舶靠离泊操纵与拖轮协同仿真' },
    { id: 'sim-port-dredge', label: '航道疏浚施工船机布置与效率仿真' },
    { id: 'sim-port-sched', label: '航运调度与时刻表优化仿真' },
    { id: 'sim-port-bridge', label: '桥区通航安全仿真（桥墩+桥底净空）' },
    { id: 'sim-port-surge', label: '港区风暴潮与极端水位对运营影响仿真' },
    { id: 'sim-port-group', label: '内河-枢纽船闸群协同运行仿真' },
    { id: 'sim-port-auto', label: '自动化港口（AGV+堆场+岸桥）协同仿真' },
    { id: 'sim-port-carbon', label: '航运碳排放与节能减排措施仿真' },
    { id: 'sim-port-evac', label: '港口疏散与应急疏运仿真' },
];

// Customer Data Management Children
const CUSTOMER_DATA_CHILDREN: MenuItem[] = [
  { id: 'cdm-master', label: '客户主数据建档与统一编码' },
  { id: 'cdm-org', label: '客户组织架构与隶属关系管理' },
  { id: 'cdm-contacts', label: '客户联系人与关键岗位画像' },
  { id: 'cdm-certs', label: '客户资质证照与合规材料管理' },
  { id: 'cdm-assets', label: '客户资产（设备）挂接与台账管理' },
  { id: 'cdm-sites', label: '客户项目/站点/码头/矿区档案管理' },
  { id: 'cdm-contracts', label: '客户合同与商务条款数据管理' },
  { id: 'cdm-workorders', label: '客户服务工单与现场处置记录' },
  { id: 'cdm-warranty', label: '质保与维保计划管理' },
  { id: 'cdm-parts', label: '备件与耗材消耗记录（客户维度）' },
  { id: 'cdm-complaints', label: '客户投诉/质量问题闭环管理' },
  { id: 'cdm-finance', label: '客户结算/对账/开票信息管理' },
  { id: 'cdm-credit', label: '客户信用额度与风险预警' },
  { id: 'cdm-security', label: '客户数据权限与共享范围控制' },
  { id: 'cdm-integration', label: '客户数据集成与同步（ERP/CRM/SCADA/IoT）' },
  { id: 'cdm-lifecycle', label: '客户生命周期管理' },
  { id: 'cdm-behavior', label: '客户行为分析与预测' },
  { id: 'cdm-satisfaction', label: '客户满意度与反馈管理' },
  { id: 'cdm-risk-compliance', label: '客户风险评估与合规性审查' },
  { id: 'cdm-delivery', label: '客户交付/运输跟踪与管理' },
  { id: 'cdm-contract-perf', label: '客户合同履约跟踪与管理' },
  { id: 'cdm-privacy', label: '客户数据安全与隐私保护' },
  { id: 'cdm-finance-payment', label: '客户财务与支付信息管理' },
  { id: 'cdm-training', label: '客户支持与培训记录' },
  { id: 'cdm-reporting', label: '客户多维度数据视图与报告' },
  { id: 'cdm-social', label: '客户社交媒体与在线互动分析' },
  { id: 'cdm-loyalty', label: '客户忠诚度与奖励管理' },
  { id: 'cdm-kb', label: '客户服务与支持案例库' },
  { id: 'cdm-supply-chain', label: '供应链与客户数据协同管理' },
  { id: 'cdm-portal', label: '客户自助服务平台与门户管理' },
  { id: 'cdm-tendering', label: '客户招投标与中标历史记录' },
  { id: 'cdm-competitors', label: '客户竞对态势与份额分析' },
  { id: 'cdm-decision-chain', label: '客户决策链与人脉关系图谱' },
  { id: 'cdm-marketing-activity', label: '客户营销活动参与记录' },
  { id: 'cdm-white-space', label: '客户空白市场与交叉销售分析' },
  { id: 'cdm-strategic-planning', label: '大客户年度战略规划' },
  { id: 'cdm-benchmark-cases', label: '客户标杆案例与样板点管理' },
  { id: 'cdm-custom-dev', label: '客户定制化开发与交付档案' },
  { id: 'cdm-channel-auth', label: '客户渠道授权与代理等级管理' },
  { id: 'cdm-churn-model', label: '客户流失预警与挽留模型' },
  { id: 'cdm-reverse-logistics', label: '客户退换货与逆向物流管理' },
  { id: 'cdm-site-visits', label: '客户现场拜访与签到记录' },
  { id: 'cdm-trial-equipment', label: '客户试用与借测设备管理' },
  { id: 'cdm-shipping-config', label: '客户包装与发货特殊要求配置' },
  { id: 'cdm-esg-profile', label: '客户ESG指标与碳排放档案' },
  { id: 'cdm-business-intel', label: '客户工商情报与舆情监控' },
  { id: 'cdm-ip-nda', label: '客户知识产权与保密协议管理' },
  { id: 'cdm-crisis-response', label: '客户应急响应与危机公关预案' },
  { id: 'cdm-digital-touchpoints', label: '客户数字化触点与访问轨迹' },
  { id: 'cdm-faq-kb', label: '客户知识库与常见问题沉淀' },
];

// Merged Remote Expert Children (Platform Capabilities + Service Scenarios)
const REMOTE_EXPERT_CHILDREN: MenuItem[] = [
  // --- Platform Core Capabilities ---
  { id: 're-profile', label: '专家资源池与画像' },
  { id: 're-matching', label: '智能匹配调度引擎' },
  { id: 're-consultation', label: '远程音视频会诊' },
  { id: 're-diagnosis', label: '智能故障诊断中心' },
  { id: 're-decision', label: '联合决策支持平台' },
  { id: 're-tickets', label: '专家工单管理系统' },
  { id: 're-collaboration', label: '专家协同工作台' },
  { id: 're-guidance', label: '远程AR作业指导' },
  { id: 're-conclusion', label: '诊断结论归档中心' },
  { id: 're-knowledge', label: '专家知识沉淀库' },
  { id: 're-compliance', label: '服务合规审计' },
  { id: 're-evaluation', label: '服务效能评估' },
  
  // --- Specific Service Scenarios ---
  { id: 'res-device-fault', label: '远程设备故障专家会诊' },
  { id: 'res-ops-anomaly', label: '远程运行异常联合研判' },
  { id: 'res-emergency-support', label: '远程应急抢险技术支援' },
  { id: 'res-accident-review', label: '远程重大事故技术复盘' },
  { id: 'res-health-eval', label: '远程设备健康状态评估' },
  { id: 'res-failure-analysis', label: '远程关键部件失效分析' },
  { id: 'res-life-prediction', label: '远程设备寿命预测与延寿评估' },
  { id: 'res-ops-optimization', label: '远程运维策略优化服务' },
  { id: 'res-complex-diag', label: '远程复杂工况诊断支持' },
  { id: 'res-param-tuning', label: '远程参数整定与性能调优' },
  { id: 'res-maintenance-review', label: '远程检修方案评审服务' },
  { id: 'res-maintenance-guide', label: '远程检修过程专家指导' },
  { id: 'res-downtime-analysis', label: '远程停机原因分析与认定' },
  { id: 'res-system-fault', label: '远程系统级联动故障诊断' },
  { id: 'res-extreme-condition', label: '远程极端工况应对支持' },
  { id: 'res-safety-risk', label: '远程安全风险评估服务' },
  { id: 'res-safety-accident', label: '远程安全事故技术鉴定' },
  { id: 'res-compliance-check', label: '远程作业规程合规性审查' },
  { id: 'res-strategy-sim', label: '远程运行策略仿真与验证' },
  { id: 'res-process-optimize', label: '远程工艺流程优化咨询' },
  { id: 'res-energy-diag', label: '远程能效分析与节能诊断' },
  { id: 'res-env-compliance', label: '远程环保排放合规评估' },
  { id: 'res-upgrade-arg', label: '远程设备升级改造论证' },
  { id: 'res-tech-route', label: '远程技术路线比选咨询' },
  { id: 'res-dt-calibration', label: '远程数字孪生模型校核' },
  { id: 'res-data-analysis', label: '远程多源运行数据深度分析' },
  { id: 'res-expert-collab', label: '远程专家协同会商服务' },
  { id: 'res-cross-region', label: '远程跨区域集中运维支撑' },
  { id: 'res-major-project', label: '远程重大项目技术把关' },
  { id: 'res-new-equipment', label: '远程新设备投运技术支持' },
  { id: 'res-commissioning', label: '远程调试与试运行专家服务' },
  { id: 'res-stability-eval', label: '远程系统稳定性评估' },
  { id: 'res-production-opt', label: '远程生产组织优化建议' },
  { id: 'res-disaster-warning', label: '远程灾害风险预警研判' },
  { id: 'res-inspection-review', label: '远程智能巡检结果复核' },
  { id: 'res-unmanned-ops', label: '远程无人化作业技术支持' },
  { id: 'res-fault-kb', label: '远程复杂故障案例库支持' },
  { id: 'res-training', label: '远程专家培训与技术传承' },
  { id: 'res-standard-guide', label: '远程行业标准解读与应用指导' },
  { id: 'res-tech-consult', label: '远程关键技术问题专项咨询' },
];
//PM——labels
const PM_LABELS = [
  "颚式破碎机主轴与轴承劣化预测", "圆锥破碎机衬板磨损趋势预测", "圆锥破碎机偏心套故障风险预测",
  "反击式破碎机转子裂纹预测", "振动筛激振器健康状态评估", "振动筛轴承疲劳寿命预测",
  "筛箱结构松动与裂纹风险预测", "筛网磨损与堵塞风险预测", "筛分系统多设备健康对比分析",
  "带式输送机整线健康状态总览", "输送带纵向撕裂风险预测", "驱动滚筒与改向滚筒磨损预测",
  "输送机减速箱振动与温升预测", "托辊故障分布与失效趋势预测", "提升机整机健康状态评估",
  "提升机钢丝绳疲劳寿命预测", "提升机制动系统可靠性预测", "提升机主轴与轴承剩余寿命预测",
  "提升机失效时间窗口预测", "球磨机整机健康状态总览", "球磨机主轴承润滑劣化预测",
  "球磨机衬板磨损趋势预测", "浮选机搅拌机构故障风险预测", "浓缩机驱动装置失效预测",
  "船舶主机整机健康状态总览", "船舶主机曲轴与主轴承健康监测", "船舶主机气缸套磨损趋势预测",
  "船舶主机活塞组件劣化评估", "船舶主机故障风险预测总览", "船舶主机故障发生概率预测",
  "船舶主机失效时间窗口预测", "船舶主机关键部件剩余寿命预测", "船舶主机剩余寿命置信区间分析",
  "船舶主机典型失效模式预测", "船舶推进轴系健康状态评估", "推进轴承振动与温升趋势预测",
  "推进轴系不对中劣化预测", "螺旋桨叶片裂纹与腐蚀预测", "推进系统劣化速度评估",
  "船舶辅机发电机健康状态总览", "船用发电机定子绕组绝缘预测", "船舶配电板与母线过热风险预测",
  "船舶电力系统负载异常预测", "船舶电力系统失效模式分析", "燃油供给系统健康状态评估",
  "燃油泵与喷油器劣化趋势预测", "燃油系统堵塞与泄漏风险预测", "润滑油系统污染与劣化预测",
  "润滑系统关键部件剩余寿命预测", "主机冷却水泵健康状态评估", "海水冷却系统结垢与腐蚀预测",
  "换热器堵塞与效率衰减预测", "压缩空气系统故障风险预测", "船舶辅助系统多设备健康对比分析",
  "舵机液压系统健康状态评估", "舵机液压泵与执行机构劣化预测", "舵机卡滞与失灵风险预测",
  "操舵系统失效时间窗口预测", "舵机关键部件剩余寿命预测", "船用绞车整机健康状态总览",
  "绞车减速箱与制动器劣化预测", "舱口盖启闭机构故障风险预测", "船用起重机回转机构健康评估",
  "甲板机械失效模式预测", "港口岸桥起重机健康状态总览", "岸桥小车与起升机构劣化预测",
  "场桥行走机构与减速箱预测维护", "航道助航灯塔供电设备健康评估", "航标设备失效风险预测",
  "重载航行工况设备劣化预测", "恶劣海况下推进系统风险预测", "高盐雾环境设备腐蚀失效预测",
  "极端气象条件设备失效预测", "连续航行工况疲劳失效预测", "多船舶设备联合故障预测",
  "船舶系统级故障传播预测", "关键航运设备级联失效预测", "预测驱动检修与靠港计划评估",
  "航运预测性维护综合评估视图"
];


// Predictive Maintenance Lists
const HYDRO_PREDICTIVE_LIST = [
  "水轮发电机组整机健康状态总览",
  "水轮机主轴与推力轴承健康监测",
  "发电机定子绕组健康指数趋势",
  "发电机转子不平衡劣化评估",
  "机组轴系振动趋势预测",
  "水轮机转轮空蚀与裂纹劣化预测",
  "导轴承与推力轴承剩余寿命预测",
  "机组故障风险预测总览",
  "机组故障发生概率与时间窗口预测",
  "机组多工况劣化演化路径分析",
  "调速器液压系统健康状态评估",
  "调速系统油泵振动与压力趋势预测",
  "导叶执行机构劣化早期识别",
  "调速系统阀组卡涩风险预测",
  "调速系统关键部件剩余寿命预测",
  "主变压器运行健康状态总览",
  "主变绕组温升与绝缘劣化预测",
  "主变油色谱异常趋势预测",
  "套管局放与绝缘老化风险评估",
  "变压器故障发生概率预测",
  "GIS 开关设备健康状态评估",
  "断路器机械特性劣化趋势预测",
  "隔离开关触头磨损风险预测",
  "母线连接点过热风险预测",
  "开关站设备失效模式预测",
  "闸门结构整体健康状态评估",
  "弧形闸门启闭机构劣化趋势预测",
  "闸门钢结构腐蚀与疲劳劣化预测",
  "闸门滚轮与滑块磨损寿命预测",
  "闸门卡阻与失灵风险预测",
  "排水泵站整机健康状态总览",
  "水泵轴承与叶轮劣化趋势预测",
  "冷却水系统泵组故障风险预测",
  "空压机与油系统设备健康评估",
  "辅机系统多设备健康对比分析",
  "压力钢管结构健康状态评估",
  "压力钢管焊缝疲劳与裂纹预测",
  "水力脉动对机组劣化影响评估",
  "水位突变工况下设备风险预测",
  "极端洪水工况设备失效预测",
  "多机组联合故障风险预测",
  "发电系统级失效传播预测",
  "水工—机电耦合失效预测",
  "电气—机械系统级风险评估",
  "关键设备级联失效预测",
  "设备预测精度与误差统计分析",
  "预测漏报与误报设备分布分析",
  "预测驱动检修计划优化评估",
  "预测性维护经济性评估",
  "水电站预测性维护综合评估视图"
];

const MINING_PREDICTIVE_LIST = [
  "电铲整机健康状态总览",
  "电铲回转机构健康状态评估",
  "电铲提升钢丝绳疲劳与断丝预测",
  "电铲提升减速箱振动趋势预测",
  "电铲主电机绝缘劣化风险预测",
  "液压挖掘机整机健康状态总览",
  "挖掘机液压泵健康指数监测",
  "挖掘机液压阀卡滞风险预测",
  "挖掘机回转轴承剩余寿命预测",
  "挖掘机动臂结构疲劳劣化预测",
  "矿用自卸卡车整车健康状态总览",
  "矿卡发动机健康状态评估",
  "矿卡变速箱与传动系统劣化预测",
  "矿卡轮边减速器故障风险预测",
  "矿卡制动系统失效时间窗口预测",
  "矿用电机车整车健康状态评估",
  "电机车牵引电机绝缘老化预测",
  "电机车齿轮箱磨损趋势预测",
  "电机车制动系统可靠性预测",
  "电机车关键部件剩余寿命预测",
  "颚式破碎机整机健康状态总览",
  // "颚式破碎机主轴与轴承劣化预测",
  // "圆锥破碎机衬板磨损趋势预测",
  // "圆锥破碎机偏心套故障风险预测",
  // "反击式破碎机转子裂纹预测",
  // "振动筛激振器健康状态评估",
  // "振动筛轴承疲劳寿命预测",
  // "筛箱结构松动与裂纹风险预测",
  // "筛网磨损与堵塞风险预测",
  // "筛分系统多设备健康对比分析",
  // "带式输送机整线健康状态总览",
  // "输送带纵向撕裂风险预测",
  // "驱动滚筒与改向滚筒磨损预测",
  // "输送机减速箱振动与温升预测",
  // "托辊故障分布与失效趋势预测",
  // "提升机整机健康状态评估",
  // "提升机钢丝绳疲劳寿命预测",
  // "提升机制动系统可靠性预测",
  // "提升机主轴与轴承剩余寿命预测",
  // "提升机失效时间窗口预测",
  // "球磨机整机健康状态总览",
  // "球磨机主轴承润滑劣化预测",
  // "球磨机衬板磨损趋势预测",
  // "浮选机搅拌机构故障风险预测",
  // "浓缩机驱动装置失效预测"
];

// const SHIP_PREDICTIVE_LIST = [
//   "船舶主机整机健康状态总览",
//   "船舶主机曲轴与主轴承健康监测",
//   "船舶主机气缸套磨损趋势预测",
//   "船舶主机活塞组件劣化评估",
//   "船舶主机故障风险预测总览",
//   "船舶主机故障发生概率预测",
//   "船舶主机失效时间窗口预测",
//   "船舶主机关键部件剩余寿命预测",
//   "船舶主机剩余寿命置信区间分析",
//   "船舶主机典型失效模式预测",
//   "船舶推进轴系健康状态评估",
//   // "推进轴承振动与温升趋势预测",
//   // "推进轴系不对中劣化预测",
//   // "螺旋桨叶片裂纹与腐蚀预测",
//   // "推进系统劣化速度评估",
//   "船舶辅机发电机健康状态总览",
//   "船用发电机定子绕组绝缘预测",
//   "船舶配电板与母线过热风险预测",
//   "船舶电力系统负载异常预测",
//   "船舶电力系统失效模式分析",
//   // "燃油供给系统健康状态评估",
//   // "燃油泵与喷油器劣化趋势预测",
//   // "燃油系统堵塞与泄漏风险预测",
//   // "润滑油系统污染与劣化预测",
//   // "润滑系统关键部件剩余寿命预测",
//   // "主机冷却水泵健康状态评估",
//   // "海水冷却系统结垢与腐蚀预测",
//   // "换热器堵塞与效率衰减预测",
//   // "压缩空气系统故障风险预测",
//   "船舶辅助系统多设备健康对比分析",
//   // "舵机液压系统健康状态评估",
//   // "舵机液压泵与执行机构劣化预测",
//   // "舵机卡滞与失灵风险预测",
//   // "操舵系统失效时间窗口预测",
//   // "舵机关键部件剩余寿命预测",
//   "船用绞车整机健康状态总览",
//   "绞车减速箱与制动器劣化预测",
//   "舱口盖启闭机构故障风险预测",
//   "船用起重机回转机构健康评估",
//   "甲板机械失效模式预测",
//   "港口岸桥起重机健康状态总览",
//   "岸桥小车与起升机构劣化预测",
//   "场桥行走机构与减速箱预测维护",
//   "航道助航灯塔供电设备健康评估",
//   "航标设备失效风险预测",
//   "重载航行工况设备劣化预测",
//   "恶劣海况下推进系统风险预测",
//   "高盐雾环境设备腐蚀失效预测",
//   "极端气象条件设备失效预测",
//   "连续航行工况疲劳失效预测",
//   "多船舶设备联合故障预测",
//   "船舶系统级故障传播预测",
//   "关键航运设备级联失效预测",
//   "预测驱动检修与靠港计划评估",
//   "航运预测性维护综合评估视图"
// ];
// Sub-menu for App Maintenance Services
const APP_MAINTENANCE_CHILDREN: MenuItem[] = [
  { id: 'am-portal', label: '维修需求提报门户' },
  { id: 'am-dispatch', label: '工单智能调度台' },
  { id: 'am-emergency', label: '紧急抢修绿色通道' },
  { id: 'am-pending', label: '挂单与延期申请处理' },
  { id: 'am-closeout', label: '维修工单核销与关闭' },
  { id: 'am-outsourcing', label: '外协服务工单跟踪' },
  { id: 'am-merge-split', label: '工单合并与拆分处理' },
  { id: 'am-timeline', label: '历史工单回溯时间轴' },
  { id: 'am-ptw', label: '电子作业票（PTW）申请' },
  { id: 'am-loto', label: 'LOTO挂牌上锁管理' },
  { id: 'am-checkin', label: '移动端接单签到' },
  { id: 'am-ar-expert', label: 'AR远程专家连线' },
  { id: 'am-sop-guide', label: '维修SOP分步执行导引' },
  { id: 'am-3d-explode', label: '3D拆装爆炸图交互' },
  { id: 'am-media-capture', label: '现场故障多媒体采集' },
  { id: 'am-test-run', label: '维修后试机记录单' },
  { id: 'am-parts-cart', label: '现场备件申领购物车' },
  { id: 'am-sn-tracking', label: '以旧换新（序列号追踪）' },
  { id: 'am-stock-alert', label: '关键备件库存预警看板' },
  { id: 'am-tools-loan', label: '维修工具借用与归还' },
  { id: 'am-parts-substitute', label: '备件替换代用审批' },
  { id: 'am-reverse-logistics', label: '逆向物流与坏件返修' },
  { id: 'am-oil-record', label: '润滑油液添加记录' },
  { id: 'am-bom-check', label: '维修BOM一致性校验' },
  { id: 'am-gantt-plan', label: '年度大修计划甘特图' },
  { id: 'am-route-config', label: '巡检路线规划与配置' },
  { id: 'am-lub-calendar', label: '润滑与保养任务日历' },
  { id: 'am-cbm-correction', label: '设备状态修正（CBM触发）' },
  { id: 'am-calibration', label: '定期精度校准记录' },
  { id: 'am-annual-inspect', label: '特种设备年检管理' },
  { id: 'am-skill-matrix', label: '维修人员技能矩阵' },
  { id: 'am-shift-roster', label: '维修排班与轮岗表' },
  { id: 'am-vendor-eval', label: '外包服务商绩效评价' },
  { id: 'am-labor-kpi', label: '维修工时绩效统计' },
  { id: 'am-training-analysis', label: '维修培训需求分析' },
  { id: 'am-asset-lcc', label: '单台设备全生命周期成本卡片' },
  { id: 'am-budget-monitor', label: '维修预算执行监控' },
  { id: 'am-warranty-mgmt', label: '索赔与质保期管理' },
  { id: 'am-roi-analysis', label: '维修投入产出比分析' },
  { id: 'am-cost-compare', label: '自行维修vs外包维修成本对比' },
  { id: 'am-incident-record', label: '维修事故与未遂事件记录' },
  { id: 'am-waste-declare', label: '废弃物处理申报' },
  { id: 'am-5s-score', label: '维修现场5S检查评分' },
  { id: 'am-ppe-mgmt', label: '个人防护装备领用' },
  { id: 'am-rcfa-report', label: '故障根因分析（RCFA）报告' },
  { id: 'am-mtbf-mttr', label: 'MTBF/MTTR趋势分析图' },
  { id: 'am-repeat-fault', label: '重复性故障识别' },
  { id: 'am-knowledge-back', label: '维修知识反哺提报' },
  { id: 'am-survey', label: '维修满意度调查问卷' },
  { id: 'am-downtime-coding', label: '停机原因编码分析' },
];

// Sub-menu for Spare Parts Services
const SPARE_PARTS_CHILDREN: MenuItem[] = [
  { id: 'sp-demand-forecast', label: '备品备件需求预测服务' },
  { id: 'sp-life-eval', label: '备品备件寿命评估服务' },
  { id: 'sp-critical-list', label: '关键备件清单构建服务' },
  { id: 'sp-std-coding', label: '备件标准化与编码服务' },
  { id: 'sp-stock-opt', label: '备件库存优化服务' },
  { id: 'sp-safety-stock', label: '安全库存配置服务' },
  { id: 'sp-substitute-match', label: '备件替代件匹配服务' },
  { id: 'sp-cert-service', label: '原厂及非原厂备件认证服务' },
  { id: 'sp-quality-trace', label: '备件质量追溯服务' },
  { id: 'sp-arrival-inspect', label: '备件到货检验服务' },
  { id: 'sp-in-service-monitor', label: '备件在役状态监测服务' },
  { id: 'sp-failure-analysis', label: '备件失效分析服务' },
  { id: 'sp-refurbish', label: '备件维修翻新服务' },
  { id: 'sp-re-manufacturing', label: '备件再制造服务' },
  { id: 'sp-lifecycle-mgmt', label: '备件全生命周期管理服务' },
  { id: 'sp-price-eval', label: '备件价格评估与比价服务' },
  { id: 'sp-risk-eval', label: '备件供应风险评估服务' },
  { id: 'sp-emergency-support', label: '备件应急保障服务' },
  { id: 'sp-turbine-parts', label: '水轮机关键备件保障服务' },
  { id: 'sp-gen-stator-rotor', label: '发电机定转子备件管理服务' },
  { id: 'sp-gate-hoist', label: '闸门及启闭机备件服务' },
  { id: 'sp-bearing-seal', label: '大型轴承与密封件备件服务' },
  { id: 'sp-hydro-hydraulic', label: '水工液压系统备件服务' },
  { id: 'sp-governor-support', label: '调速系统备件保障服务' },
  { id: 'sp-automation-sys', label: '电站自动化系统备件服务' },
  { id: 'sp-sensors', label: '水电站专用传感器备件服务' },
  { id: 'sp-metal-structure', label: '水工金属结构备件服务' },
  { id: 'sp-flood-emergency', label: '防汛抢险备件应急服务' },
  { id: 'sp-localization-sub', label: '老旧水电站备件国产化替代服务' },
  { id: 'sp-maintenance-planning', label: '水电设备停机检修备件统筹服务' },
  { id: 'sp-ship-main-engine', label: '船舶主机备件服务' },
  { id: 'sp-ship-auxiliary', label: '船舶辅机系统备件服务' },
  { id: 'sp-ship-propulsion', label: '船用推进系统备件服务' },
  { id: 'sp-ship-electrical', label: '船舶电气系统备件服务' },
  { id: 'sp-ship-automation-nav', label: '船舶自动化与导航设备备件服务' },
  { id: 'sp-ship-safety-parts', label: '船舶关键安全备件保障服务' },
  { id: 'sp-class-cert', label: '船级社认证备件服务' },
  { id: 'sp-shipping-emergency', label: '航运应急抢修备件快速供应服务' },
  { id: 'sp-mining-critical', label: '采掘设备关键备件服务' },
  { id: 'sp-crush-screen', label: '破碎与筛分设备备件服务' },
  { id: 'sp-conveying-sys', label: '输送系统备件服务' },
  { id: 'sp-mine-hydraulic', label: '矿用液压系统备件服务' },
  { id: 'sp-mine-motor-inv', label: '矿山电机与变频器备件服务' },
  { id: 'sp-mine-bearing', label: '矿用重载轴承备件服务' },
  { id: 'sp-mine-monitor', label: '矿山安全监测设备备件服务' },
  { id: 'sp-mine-wear-parts', label: '矿山耐磨件备件服务' },
  { id: 'sp-underground-emergency', label: '井下设备应急备件保障服务' },
  { id: 'sp-mine-localization', label: '矿山设备国产化替代与改造备件服务' },
  { id: 'sp-procurement-collab', label: '备件采购协同服务' },
  { id: 'sp-warehouse-automation', label: '仓储自动化升级服务' },
];

// Helper to create children array
const createPredictiveChildren = (list: string[], prefix: string): MenuItem[] => {
  return list.map((label, index) => ({
    id: `pm-${prefix}-${index}`,
    label
  }));
};
const KNOWLEDGE_MANAGE_CHILDREN: MenuItem[] = [
  { id: 'km-watershed-dispatch', label: '流域梯级调度规则引擎' },
  { id: 'km-dam-seepage', label: '大坝渗流热力学反演模型库' },
  { id: 'km-turbine-cavitation', label: '水轮机汽蚀破坏案例图谱' },
  { id: 'km-flood-discharge', label: '泄洪消能防冲经验库' },
  { id: 'km-eco-flow', label: '生态流量合规性知识图谱' },
  { id: 'km-generator-insulation', label: '发电机组绝缘老化特征库' },
  { id: 'km-underwater-robot', label: '水工建筑物水下机器人检测图鉴' },
  { id: 'km-flood-emergency', label: '极端洪水应急预案演练脚本库' },
  { id: 'km-sedimentation', label: '库区泥沙淤积演变历史档案' },
  { id: 'km-black-start', label: '黑启动操作逻辑库' },
  { id: 'km-trash-rack', label: '进水口拦污栅压差阈值标准' },
  { id: 'km-freeze-thaw', label: '寒冷地区防冻融技术规范库' },
  { id: 'km-hoist-fault', label: '大型启闭机液压系统故障树' },
  { id: 'km-economic-operation', label: '水电站经济运行策略库' },
  { id: 'km-slope-disaster', label: '库岸边坡地质灾害机理库' },
  { id: 'km-stilling-basin', label: '水下消力池磨损修复工艺库' },
  { id: 'km-fish-passage', label: '过鱼设施运行效能档案' },
  { id: 'km-lock-dispatch', label: '船闸通航联合调度算法库' },
  { id: 'km-channel-shoal', label: '航道浅滩演变与疏浚知识库' },
  { id: 'km-crane-fatigue', label: '港口岸桥金属结构疲劳寿命档案' },
  { id: 'km-ais-behavior', label: '船舶自动识别系统异常行为特征库' },
  { id: 'km-dangerous-goods', label: '危险货物集装箱隔离堆存规则库' },
  { id: 'km-agv-deadlock', label: '港口自动化引导车路径死锁案例库' },
  { id: 'km-buoy-drift', label: '助航灯浮标漂移规律库' },
  { id: 'km-ship-impact', label: '船舶靠泊撞击力经验参数库' },
  { id: 'km-vts-plan', label: 'VTS交通组织预案库' },
  { id: 'km-green-port-power', label: '绿色港口岸电连接兼容性档案' },
  { id: 'km-maritime-accident', label: '水上交通事故判例与法规库' },
  { id: 'km-crane-wind', label: '集装箱装卸桥防风锚定策略库' },
  { id: 'km-dust-suppression', label: '散货堆场抑尘喷淋策略库' },
  { id: 'km-tunnel-joint', label: '水下隧道沉管接头健康诊断模型' },
  { id: 'km-pilot-exp', label: '引航员特殊水域操作经验集' },
  { id: 'km-multimodal', label: '多式联运接口标准库' },
  { id: 'km-unmanned-ship', label: '无人船巡航避障算法训练集' },
  { id: 'km-hydraulic-support', label: '综采工作面液压支架阻力分布图谱' },
  { id: 'km-truck-tire', label: '矿用自卸卡车轮胎磨损与路面关联库' },
  { id: 'km-belt-tear', label: '皮带输送机纵向撕裂视觉样本库' },
  { id: 'km-ventilation-network', label: '井下通风网络解算模型库' },
  { id: 'km-crushing-index', label: '矿石破碎功指数档案' },
  { id: 'km-shovel-tooth', label: '电铲斗齿脱落智能识别特征库' },
  { id: 'km-tailings-safety', label: '尾矿库干滩长度与浸润线安全阈值库' },
  { id: 'km-ground-pressure', label: '深井地压冲击前兆特征库' },
  { id: 'km-explosion-proof', label: '矿用防爆设备电气整定值计算逻辑' },
  { id: 'km-flotation-reagent', label: '浮选药剂添加配比专家系统' },
  { id: 'km-shearer-pick', label: '采煤机截齿截割阻力模型' },
  { id: 'km-vehicle-path', label: '无轨胶轮车井下路径规划图谱' },
  { id: 'km-rope-ndt', label: '提升机钢丝绳无损探伤缺陷图谱' },
  { id: 'km-slope-radar', label: '露天矿边坡雷达位移预警模型' },
  { id: 'km-mill-liner', label: '磨机衬板钢球级配优化档案' },
  { id: 'km-water-inrush', label: '井下突水水源快速判别知识库' },
  { id: 'km-blasting-control', label: '矿山爆破参数优化与震动控制库' },
  { id: 'km-truck-edge', label: '无人矿卡边缘场景库' },
  { id: 'km-scraper-chain', label: '刮板输送机链条张力动态平衡策略' }
];

// Flattened Service Data Management Items (Now 50 items)
const SERVICE_DATA_FLAT_CHILDREN: MenuItem[] = [
  // 矿山板块 (10 + 3 = 13项)
  { id: 'sm-1', label: '露天矿与井工矿大型采掘装备运行服务数据管理' },
  { id: 'sm-2', label: '矿山破碎、输送、提升系统运维服务数据管理' },
  { id: 'sm-3', label: '矿用电铲、液压支架、采煤机服务过程数据管理' },
  { id: 'sm-4', label: '矿山装备高粉尘高振动工况服务数据管理' },
  { id: 'sm-5', label: '矿山装备故障停机与抢修服务数据管理' },
  { id: 'sm-6', label: '矿山多工作面协同运维服务数据管理' },
  { id: 'sm-7', label: '矿山装备关键部件寿命与更换服务数据管理' },
  { id: 'sm-8', label: '矿山无人化装备远程运维服务数据管理' },
  { id: 'sm-9', label: '矿山多厂家装备服务数据统一管理' },
  { id: 'sm-10', label: '矿山装备检修计划与执行闭环数据管理' },
  { id: 'sm-11', label: '矿山装备智能巡检与服务数据管理' },
  { id: 'sm-12', label: '矿山极端工况与安全保障服务数据管理' },
  { id: 'sm-13', label: '矿山能源消耗与设备服务数据管理' },
  
  // 航运板块 (10 + 3 = 13项)
  { id: 'sh-1', label: '船舶主机与辅机系统运行服务数据管理' },
  { id: 'sh-2', label: '船舶航行状态与能效服务数据管理' },
  { id: 'sh-3', label: '船舶设备复杂海况适应性服务数据管理' },
  { id: 'sh-4', label: '船舶在役监测与预测性维护服务数据管理' },
  { id: 'sh-5', label: '船舶靠离泊与港口协同服务数据管理' },
  { id: 'sh-6', label: '港口装卸与配套装备运维服务数据管理' },
  { id: 'sh-7', label: '航道设施巡检与养护服务数据管理' },
  { id: 'sh-8', label: '船岸协同条件下航运装备服务数据管理' },
  { id: 'sh-9', label: '多船队多航线运行服务数据集中管理' },
  { id: 'sh-10', label: '航运装备应急故障与抢修服务数据管理' },
  { id: 'sh-11', label: '船舶设备能效优化与服务数据管理' },
  { id: 'sh-12', label: '船舶关键系统可靠性评估服务数据管理' },
  { id: 'sh-13', label: '航运装备跨周期服役服务数据管理' },
  
  // 水电板块 (10 + 3 = 13项)
  { id: 'hd-1', label: '水电站机组运行状态服务数据管理' },
  { id: 'hd-2', label: '水轮机与发电机系统运维服务数据管理' },
  { id: 'hd-3', label: '水电设备长期连续运行工况服务数据管理' },
  { id: 'hd-4', label: '水电站检修窗口期与资源调度服务数据管理' },
  { id: 'hd-5', label: '水库调度指令执行与反馈服务数据管理' },
  { id: 'hd-6', label: '水工建筑物巡检与结构健康服务数据管理' },
  { id: 'hd-7', label: '水电站设备异常与事故处置服务数据管理' },
  { id: 'hd-8', label: '梯级水电站联合运行服务数据管理' },
  { id: 'hd-9', label: '跨区域水利工程运行维护服务数据管理' },
  { id: 'hd-10', label: '水电站数字化移交后服务数据接管管理' },
  { id: 'hd-11', label: '水电设备状态评估与健康管理服务数据管理' },
  { id: 'hd-12', label: '水电站设备寿命预测服务数据管理' },
  { id: 'hd-13', label: '水电站应急调度与保障服务数据管理' },
  
  // 综合板块 (5 + 6 = 11项)
  { id: 'int-1', label: '矿山航运水利装备服务数据统一汇聚与治理' },
  { id: 'int-2', label: '装备服务数据与运行工况协同管理' },
  { id: 'int-3', label: '装备服务数据驱动的运维决策支持' },
  { id: 'int-4', label: '装备服务知识沉淀与复用数据管理' },
  { id: 'int-5', label: '装备全生命周期服务数据反哺设计与改进' },
  { id: 'int-6', label: '装备服务数据质量评估与治理' },
  { id: 'int-7', label: '装备服务数据分级分类与权限管理' },
  { id: 'int-8', label: '装备服务数据安全与合规管理' },
  { id: 'int-9', label: '装备服务数据多源融合与共享' },
  { id: 'int-10', label: '装备服务数据驱动的智能分析' },
  { id: 'int-11', label: '装备服务数据支撑的服务模式优化' },
];


export const MENU_ITEMS: MenuItem[] = [
  { 
    id: 'smart-ops', 
    label: '工业智能运维',
    children: SMART_OPS_CHILDREN
  },
  { 
    id: 'product-kb', 
    label: '工业产品知识库',
    children: PRODUCT_KB_CHILDREN
  },
  { 
    id: 'cockpit', 
    label: '运行驾驶舱',
    children: COCKPIT_CHILDREN
  },
  { 
    id: 'index-analysis', 
    label: '运行指数分析',
    children: INDEX_ANALYSIS_CHILDREN
  },
  { 
    id: 'digital-delivery', 
    label: '数字化交付',
    children: DIGITAL_DELIVERY_CHILDREN
  },
  { 
    id: 'simulation', 
    label: '仿真分析',
    children: SIMULATION_CHILDREN
  },
  { id: 'customer-data', 
    label: '客户数据管理',
    children: CUSTOMER_DATA_CHILDREN },
  { id: 'remote-expert', 
    label: '远程专家服务',
    children: REMOTE_EXPERT_CHILDREN },
  { 
    id: 'predictive-maintenance', 
    label: '预测性维护',
    children: [
        ...createPredictiveChildren(HYDRO_PREDICTIVE_LIST, 'hydro'),
        ...createPredictiveChildren(MINING_PREDICTIVE_LIST, 'mining'),
        //...createPredictiveChildren(SHIP_PREDICTIVE_LIST, 'ship'),
        ...createPredictiveChildren(PM_LABELS, 'pmOther'),
    ]
  },

  { 
    id: 'app-maintenance', 
    label: '应用维修服务',
    children: APP_MAINTENANCE_CHILDREN
  },
  { 
    id: 'spare-parts', 
    label: '备品备件服务',
    children: SPARE_PARTS_CHILDREN
  },
  { 
    id: 'mock-maintenance', 
    label: '模拟维修服务',
    children: [
      { id: 'mm-01', label: '水轮发电机组虚拟拆装与检修演练' },
      { id: 'mm-02', label: '水电站主变压器故障模拟与维修推演' },
      { id: 'mm-03', label: '闸门启闭机结构损伤模拟维修' },
      { id: 'mm-04', label: '水轮机叶片空蚀修复过程仿真' },
      { id: 'mm-05', label: '水电站轴承系统寿命退化与更换模拟' },
      { id: 'mm-06', label: '船舶主机系统虚拟检修演练' },
      { id: 'mm-07', label: '船舶推进轴系故障模拟维修' },
      { id: 'mm-08', label: '船舶电力系统异常工况维修仿真' },
      { id: 'mm-09', label: '港口起重设备关键部件虚拟维护' },
      { id: 'mm-10', label: '航道疏浚设备液压系统维修模拟' },
      { id: 'mm-11', label: '船闸机电设备综合维修仿真' },
      { id: 'mm-12', label: '矿用破碎机结构损伤模拟维修' },
      { id: 'mm-13', label: '矿山提升机钢丝绳失效更换模拟' },
      { id: 'mm-14', label: '矿用皮带输送系统故障维修演练' },
      { id: 'mm-15', label: '矿山通风系统设备虚拟检修' },
      { id: 'mm-16', label: '矿用液压支架关键部件维修仿真' },
      { id: 'mm-17', label: '矿山排水泵站故障诊断与维修模拟' },
      { id: 'mm-18', label: '矿用钻机动力系统拆解维修演练' },
      { id: 'mm-19', label: '矿山电铲关键机构虚拟维护' },
      { id: 'mm-20', label: '矿用发动机故障维修过程仿真' },
      { id: 'mm-21', label: '水电站年度检修方案模拟与优化' },
      { id: 'mm-22', label: '船舶坞修全过程虚拟演练' },
      { id: 'mm-23', label: '港口设备多工种协同维修仿真' },
      { id: 'mm-24', label: '矿山设备大修方案可行性模拟' },
      { id: 'mm-25', label: '水轮机运行异常快速维修决策模拟' },
      { id: 'mm-26', label: '船舶关键设备应急维修推演' },
      { id: 'mm-27', label: '矿山突发设备停机应急维修演练' },
      { id: 'mm-28', label: '水电站远程专家辅助维修模拟' },
      { id: 'mm-29', label: '船舶设备跨区域远程维修协同模拟' },
      { id: 'mm-30', label: '矿山无人值守设备虚拟检修' },
      { id: 'mm-31', label: '水电站设备检修工艺标准化仿真' },
      { id: 'mm-32', label: '船舶老旧设备维修可行性评估模拟' },
      { id: 'mm-33', label: '矿山装备改造前维修路径仿真' },
      { id: 'mm-34', label: '水电设备检修人员培训模拟系统' },
      { id: 'mm-35', label: '航运设备新手维修技能训练仿真' },
      { id: 'mm-36', label: '矿山复杂故障多方案维修对比模拟' },
      { id: 'mm-37', label: '水电站关键备件更换时序模拟' },
      { id: 'mm-38', label: '船舶设备寿命末期维修策略推演' },
      { id: 'mm-39', label: '矿山设备全生命周期维修成本模拟' },
      { id: 'mm-40', label: '水电站数字孪生维修场景构建' },
      { id: 'mm-41', label: '船舶设备维修风险评估模拟' },
      { id: 'mm-42', label: '矿山装备维修安全演练仿真' },
      { id: 'mm-43', label: '水电站设备快速复役维修模拟' },
      { id: 'mm-44', label: '港口设备全天候维修策略仿真' },
      { id: 'mm-45', label: '矿山装备维修工序冲突消解模拟' },
      { id: 'mm-46', label: '跨系统设备联合维修协同仿真' },
    ]
  },
  { 
    id: 'ops-knowledge', 
    label: '运维知识管理',
    children: KNOWLEDGE_MANAGE_CHILDREN
  },
  { //2026.01.19, update
    id: 'service-data', 
    label: '服务数据管理',
    children: SERVICE_DATA_FLAT_CHILDREN
  },
  { id: 'inspection', label: '设备点巡检' },
  { id: 'maintenance-plan', label: '维修计划管理' },
  { id: 'life-warning', label: '零部件寿命预警' },
  { id: 'cv-monitor', label: '计算机视觉监测' },
  { id: 'vibration-monitor', label: '震动监测' },
  { id: 'maintenance-training', label: '维修培训' },
];
