/**
 * 全站可见文本中文化兜底。
 *
 * 项目包含大量独立场景组件，且图表、三维视图和弹窗中的文案并不都经过
 * 同一套组件。这里对已经渲染出来的内容做最后一道本地化处理，确保后续
 * 新增或遗漏的英文标签不会直接暴露给用户。数值单位会按白名单保留。
 */

type LocalizableRoot = HTMLElement | ShadowRoot;

const UNIT_TOKENS = new Set([
  '%', 'a', 'bar', 'cm', 'db', 'g', 'gb', 'gb/s', 'gw', 'h', 'hz', 'j', 'kg',
  'khz', 'km', 'kn', 'knm', 'kpa', 'kv', 'kw', 'kwh', 'l', 'l/min', 'm', 'ma',
  'mb', 'mb/s', 'mg', 'mhz', 'min', 'ml', 'mm', 'mm/s', 'mn', 'mpa', 'ms', 'mv',
  'mw', 'mwh', 'n', 'nm', 'nt', 'ntu', 'pa', 'ph', 'ppb', 'ppm', 'rpm', 's',
  'sec', 't', 'v', 'w', 'wh',
]);

/**
 * 需要按完整语义翻译的界面文案。这里优先采用国内工业软件常用说法，
 * 避免把标题、按钮和业务字段拆成若干单词后机械拼接。
 */
const EXACT_TEXT: Record<string, string> = {
  'pipe burst': '管道爆裂',
  'pressure low': '压力偏低',
  'pump trip': '水泵跳闸',
  'node-452 (main st)': 'Node-452（主街道）',
  'dma-03 sensor': 'DMA-03传感器',
  'station b #2': 'B站2号设备',
  'rescue team alpha': 'A组救援队',
  'rescue team bravo': 'B组救援队',
  'medical unit': '医疗救援组',
  'loc: tunnel main junction': '位置：主隧道交汇处',
  'loc: surface base': '位置：地面基地',
  'loc: triage tent': '位置：检伤分类帐篷',
  'advancing': '正在前进',
  'standby': '待命',
  'ready': '就绪',
  'reservoir a': 'A水库',
  'reservoir b': 'B水库',
  'reservoir c': 'C水库',
  'unified code': '统一编码',
  'customer name': '客户名称',
  'government': '政府机构',
  'enterprise': '企业客户',
  'individual': '个人客户',
  'east china': '华东地区',
  'north china': '华北地区',
  'south china': '华南地区',
  'west china': '西部地区',
  'overseas': '海外',
  'municipal transport bureau': '市交通运输局',
  'global logistics corp.': '环球物流公司',
  'autoworks gmbh': '汽车工业有限公司',
  'quantum chip tech': '量子芯片科技',
  'wang j.': '王先生',
  'slope stabilization a': 'A区边坡加固',
  'soil remediation b': 'B区土壤修复',
  'wetland construction': '湿地建设',
  'wang engineer': '王工程师',
  'dr. zhang wei': '张伟博士',
  'dr. wang': '王博士',
  'sarah li': '李莎拉',
  'sarah wu': '吴莎拉',
  'elena wu': '吴艾琳',
  'pipe burst alert': '管道爆裂告警',
  'vibration alert': '振动告警',
  'abnormal vibration': '振动异常',
  'within tol': '在允许偏差范围内',
  'diff current': '差动电流',
  'red indicates critical failure path': '红色表示严重故障路径',
  'active archival range': '当前归档范围',
  'active constraints': '当前生效约束',
  'active instructions': '当前指令',
  'actor identity': '操作主体身份',
  'add argument': '添加意见',
  'add argument...': '请输入意见…',
  'add new connector': '新增连接器',
  'adhesion failure due to high operating temp (>120°c).': '运行温度过高（>120°C）导致粘接失效。',
  'adiabatic base': '绝热底边界',
  'advance dist': '推进距离',
  'advanced re-genesis facility': '高级再制造中心',
  'advanced remanufacturing lab': '高级再制造实验室',
  'aft stern tube': '艉轴管',
  'after spray': '喷雾后',
  'ai copilot': '智能助手',
  'ai driver monitor': '智能驾驶员监测',
  'ai vision core active': '智能视觉核心运行中',
  'air door closed': '风门已关闭',
  'alignment deviance': '对中偏差',
  'analyze frequency spectrum': '分析频谱',
  'annual churn': '年度客户流失率',
  'approaching berth': '正在靠泊',
  'approve & publish': '审批并发布',
  'aquifer seepage': '含水层渗流',
  'assembled state': '装配状态',
  'asset cards': '资产卡片',
  'asset continuity': '资产连续性',
  'asset vitality center': '资产健康中心',
  'attach file': '添加附件',
  'auth success': '认证成功',
  'auth token': '认证令牌',
  'automated workflow handoff': '自动化工作流移交',
  'autonomous haulage system ready': '无人运输系统就绪',
  'autonomy 15 days': '续航15天',
  'avg beam stress': '平均梁应力',
  'avg salinity': '平均盐度',
  'avg transit time': '平均运输时长',
  'baihetan station': '白鹤滩电站',
  'bank transfer - partial': '银行转账—部分到账',
  'bearing node warning: lubrication degrading': '轴承节点告警：润滑状态下降',
  'bearings monitoring active': '轴承监测运行中',
  'beijing r&d center': '北京研发中心',
  'best eff': '最佳效率',
  'biometric auth required': '需要生物识别认证',
  'blacklist status': '黑名单状态',
  'brakes ok': '制动系统正常',
  'bridge clearance': '桥下净空',
  'bucket fill': '铲斗装载率',
  'bucket linkage': '铲斗连杆机构',
  'business license': '营业执照',
  'category': '类别',
  'client': '客户',
  'convergence': '收敛状态',
  'copper (ppm)': '铜含量（ppm）',
  'iron (ppm)': '铁含量（ppm）',
  'done': '已完成',
  'dumping': '卸载中',
  'empty': '空载',
  'expiring': '即将到期',
  'generating': '发电中',
  'hauling': '运输中',
  'heading': '航向',
  'idle': '空闲',
  'labor': '人工服务',
  'matched': '已匹配',
  'measured': '实测值',
  'missing': '缺失',
  'ore tonnage': '矿石吨数',
  'other': '其他',
  'planned': '已计划',
  'rejected': '已驳回',
  'return (empty)': '空载返回',
  'row 1': '第1排',
  'row 2': '第2排',
  'row 3': '第3排',
  'skills': '技能',
  'solutions': '解决方案',
  'speaking': '发言中',
  'symptom': '故障现象',
  'unassigned': '未分配',
  'yesterday': '昨天',
  'dr. zhang': '张博士',
  'mike chen': '陈迈克',
  'off': '关闭',
  'pause': '暂停',
  'allowed': '允许',
  'elec': '电力',
  'crashed': '已碰撞',
  'lower': '较低值更优',
  'maint': '维护中',
  'media': '媒体资料',
  'merge': '合并',
  'user': '用户',
  'video': '视频',
  'warn': '告警',
  'approved': '已批准',
  'auto-check': '自动校验',
  'balanced': '均衡',
  'bedrock': '基岩',
  'brief': '简报',
  'cap': '容量',
  'disputed': '存在争议',
  'explode': '分解',
  'formal': '正式',
  'fri': '周五',
  'host': '主持人',
  'linking': '关联中',
  'methanol': '甲醇',
  'mon': '周一',
  'multi-dimensional': '多维分析',
  'muted': '已静音',
  'owns 100%': '持股100%',
  'people': '人',
  'rebooting': '正在重启',
  'recovered': '已恢复',
  'restricted': '受限',
  'thu': '周四',
  'thumb': '缩略图',
  'tue': '周二',
  'wed': '周三',
  'whiteboard': '白板',
  'x-ray': 'X射线',
  '!! intrusion !!': '!! 检测到入侵 !!',
  '(2 crit)': '（2项严重问题）',
  '(rough)': '（恶劣海况）',
  '• overcurrent': '• 过电流',
  '2021-01 / 2024-present': '2021-01 / 2024年至今',
  '30% blocked': '堵塞率30%',
  '50% blocked': '堵塞率50%',
  '58 (fair)': '58（一般）',
  '98.5% (strong)': '98.5%（强）',
  'abnormal': '异常',
  'abnormal buoys': '异常航标',
  'qingdao qqctn': '青岛QQCTN码头',
  'sts cranes': '岸桥',
  'sensor calibration sop': '传感器标定标准作业程序',
  '"at risk" customer user_9921 abandoned cart. schedule proactive support call.': '高风险客户 User_9921 放弃了购物车，建议主动安排回访。',
  '"loyal" segment usage spike. suggest enterprise plan upgrade.': '忠诚客户群使用量显著增长，建议升级企业套餐。',
  '"need better spare parts availability next time."': '“希望下次能够更及时地提供备件。”',
  '"response time was excellent. tech arrived within 4 hours."': '“响应非常及时，技术人员在4小时内到达。”',
  '"system latency during peak hours" mentioned by 15% of enterprise users this week.': '本周有15%的企业用户反馈“高峰时段系统延迟”。',
  '(load reduction) yields the highest success rate (82%) with minimal long-term damage.': '“降低负载”方案成功率最高（82%），且长期损伤最小。',
  '(vibration alert) - 2h ago': '振动告警—2小时前',
  '(within tol).': '在允许偏差范围内。',
  '[10:45:02] sys: dau-01 handshake ok.': '[10:45:02] 系统：DAU-01 通信握手正常。',
  '+++ 2023-10-24 14:30: warning: slight pressure drop in compressed air line section b-4 +++ personnel tracking active +++': '+++ 2023-10-24 14:30：告警：B-4段压缩空气管路压力轻微下降 +++ 人员定位系统运行中 +++',
  '| blasting ops': '｜爆破作业',
  '● hydrophilic (waste)': '● 亲水性（废料）',
  '● hydrophobic (ore)': '● 疏水性（矿石）',
  '1 pc (low)': '1件（库存偏低）',
  '10 stemmed / 5 loading...': '已堵塞10孔 / 正在装药5孔…',
  '45% of l1 tickets were solved via knowledge base articles this week, freeing up l3 experts.': '本周45%的一级工单已通过知识库解决，从而释放了三级专家资源。',
  '500h service due in 15 days. order lubricant pack #lub-x99.': '距500小时保养还有15天，请订购润滑包 #LUB-X99。',
  'access to aggregated/anonymized datasets only.': '仅允许访问汇总或匿名化数据集。',
  'acknowledged. the 2.4khz modulation is clear. however, checking lubrication records first.': '收到。2.4kHz调制特征清晰，但应先核查润滑记录。',
  'ai detected inner race fault.': '智能诊断检测到轴承内圈故障。',
  'ai model predicts 85% chance of blade crack propagation within 4 hours.': '智能模型预测叶片裂纹在4小时内扩展的概率为85%。',
  'ai reasoning engine v2.4 • click nodes to view detailed diagnostic steps': '智能推理引擎 v2.4 • 点击节点查看详细诊断步骤',
  'alert: high gmf1 amplitude indicating potential tooth pitting on sun gear 1.': '告警：GMF1幅值偏高，表明1号太阳轮可能存在齿面点蚀。',
  'arrived at site. gps verified. safety briefing completed.': '已到达现场，卫星定位验证通过，安全交底已完成。',
  'asset is currently under manufacturer warranty. maintenance requires authorized personnel.': '该资产仍在制造商质保期内，维护工作须由授权人员执行。',
  'asset scheduled for renewal in 2028 based on current residual value projections.': '根据当前残值预测，该资产计划于2028年更新。',
  'attempt to recalibrate sensors while running. high risk if actual mechanical failure.': '尝试在运行中重新标定传感器；如确有机械故障，该操作风险较高。',
  'audio analysis detected 2 potential risk keywords during the session. human review recommended.': '音频分析在本次会话中检出2个潜在风险关键词，建议人工复核。',
  'auto-assigned to nearest qualified engineer wang.': '已自动指派给距离最近且资质匹配的王工程师。',
  'based on quartz/granite abrasion index (ai=0.45)': '依据石英/花岗岩磨蚀指数（Ai=0.45）',
  'based on thermal class f (155°c) and current operating temp average of 135°c.': '基于F级绝缘耐热等级（155°C）及当前平均运行温度135°C。',
  'batch #8821 completed successfully.': '批次 #8821 已成功完成。',
  'batch #8821 started. fetching updated contacts.': '批次 #8821 已启动，正在获取更新后的联系人信息。',
  'batch size is small (12 recs). consider increasing to 50 for better throughput.': '当前批次较小（12条），建议增至50条以提升吞吐效率。',
  'bathymetry update: depth 12.8m at beacon 01.': '水深测量更新：01号航标处水深12.8m。',
  'block b-02: reefer temperature alarm active. tech dispatched.': 'B-02区冷藏箱温度告警已触发，技术人员已派出。',
  'broadband noise detected in 1khz-5khz range indicates active bubble collapse.': '1kHz至5kHz频段检测到宽带噪声，表明气泡破裂活动明显。',
  'can view/edit pii, approve sharing requests.': '可查看和编辑个人敏感信息，并审批共享申请。',
  'check the coupling alignment first.': '请先检查联轴器对中情况。',
  'cluster "promising" showing high interest in model x. send 10% discount coupon now.': '潜力客户群对 X 型产品兴趣较高，建议立即发放九折优惠券。',
  'cold cylinder detected. likely solenoid failure or nozzle clogging.': '检测到冷缸，可能由电磁阀故障或喷嘴堵塞引起。',
  'combined rainfall and pore pressure rise has reduced factor of safety below critical threshold.': '降雨与孔隙水压力共同上升，已导致安全系数降至临界阈值以下。',
  'compare spot market price vs. estimated future value of stored water.': '比较现货市场价格与蓄水未来价值估算。',
  'complex issues may require multi-expert consultation. enable "panel mode" to invite multiple specialists.': '复杂问题可能需要多专家会诊，请启用“专家组模式”邀请多位专家。',
  'confirmed. amplitude increased 20% in last 2 hours. suggest immediate shutdown for inspection.': '确认。振幅在最近2小时内上升20%，建议立即停机检查。',
  'container loaded onto vessel.': '集装箱已装船。',
  'corrective action: replace valve type, add vibration dampeners, update inspection interval to 3 months.': '纠正措施：更换阀门型号，增设减振器，并将巡检周期调整为3个月。',
  'credit utilization > 95% for 3 consecutive months.': '授信额度使用率已连续3个月超过95%。',
  'current price is high. recommend increasing discharge to capture revenue, provided flood limit is not breached.': '当前电价较高，在不突破防洪限制的前提下，建议增加下泄流量以提高收益。',
  'master data management': '主数据管理',
  'total records': '记录总数',
  'data quality score': '数据质量评分',
  'new today': '今日新增',
  'non-standard code format': '非标准编码格式',
  'unified social credit code structure': '统一社会信用代码结构',
  'lifecycle status': '生命周期状态',
  'tax id': '纳税识别号',
  'credit rating': '信用等级',
  'view history': '查看历史记录',
  'erp sync status': '企业资源管理系统同步状态',
  'coding compliance': '编码合规率',
  'active layer': '当前图层',
  'active maintenance ticket': '当前维修工单',
  'active plans': '生效计划',
  'active protocols': '启用协议',
  'active shipments': '在途货物',
  'active shipment': '在途货物',
  'active signals': '活跃信号',
  'active stations': '运行站点',
  'active targets': '活动目标',
  'active trucks': '运行车辆',
  'air compressor': '空气压缩机',
  'air quality: good': '空气质量：良好',
  'available experts': '可用专家',
  'available templates': '可用模板',
  'bank name': '开户银行',
  'bearing overheat warning': '轴承过热预警',
  'belt tear risk': '皮带撕裂风险',
  'bulk material logistics': '散货物流',
  'burst detected': '检测到管道爆裂',
  'daily supply': '日供水量',
  'avg pressure': '平均压力',
  'outflow turbidity': '出水浊度',
  'residual cl': '余氯',
  'pump station a load': 'A泵站负载',
  'clear water tank': '清水池',
  'pressure pass': '压力合格率',
  'repair time': '平均抢修时间',
  'smart meters online': '智能水表在线率',
  'pacific power group': '太平洋电力集团',
  'shanghai heavy ind.': '上海重工',
  'shanghai heavy industries': '上海重工',
  'shanghai heavy industries ltd.': '上海重工有限公司',
  'quantum tech': '量子科技',
  'north star logistics': '北极星物流',
  'autoworks global': '环球汽车工业',
  'blue sky energy': '蓝天能源',
  'global shipping inc.': '环球航运公司',
  'nanjing logistics co.': '南京物流公司',
  'nano dynamics': '纳米动力科技',
  'elapsed time': '已用时间',
  'explode view': '分解视图',
  'exploded view': '分解视图',
  'our solution': '我方方案',
  'current ops': '当前运行情况',
  'just now': '刚刚',
  'on track': '进展正常',
  'safety officer': '安全负责人',
  'specific energy': '单位能耗',
  'executive summary': '管理摘要',
  'fresh air': '新风',
  'gemini reasoning core': '智能推理核心',
  'ice thickness': '冰层厚度',
  'industrial knowledge base': '工业知识库',
  'knowledge_integrity: certified': '知识完整性：已认证',
  'optimization tip': '优化建议',
  'success rate': '成功率',
  'sump level': '集水池水位',
  'type message...': '请输入消息…',
  'x-ray active': 'X射线检测中',
  '24/7 predictive shield activated': '全天候预测防护已启用',
  'active power (p)': '有功功率（P）',
  'reactive power (q)': '无功功率（Q）',
  'active sessions': '活跃会话数',
  'active vessels': '在航船舶数',
  'add note or update...': '添加备注或进展…',
  'ai insight:': '智能分析：',
  'automation lead': '自动化负责人',
  'avg resolution time': '平均解决时长',
  'bearing seal rubbing': '轴承密封摩擦',
  'billing team': '结算团队',
  'bond law & comminution': '邦德功耗理论与粉碎工艺',
  'braking active': '制动系统工作中',
  'cases solved': '已解决案例',
  'cavitation bubbles': '空化气泡',
  'collision risk': '碰撞风险',
  'computer vision lab': '计算机视觉实验室',
  'contact resistance': '接触电阻',
  'control sys': '控制系统',
  'cost per lead': '单条线索成本',
  'cost saving': '成本节约额',
  'create work order': '创建工单',
  'credit score': '信用评分',
  'current fos': '当前安全系数',
  'dielectric loss (tgδ)': '介质损耗（tgδ）',
  'discharge (q)': '流量（Q）',
  'display filter set': '显示筛选设置',
  'durability factor': '耐久性系数',
  'early adopter': '早期使用客户',
  'eco score': '环保评分',
  'economic buyer': '采购决策人',
  'emergency shutdown (esd) engaged.': '紧急停机系统（ESD）已动作。',
  'end of life (200)': '寿命终点（200）',
  'endpoint status': '接口端点状态',
  'esd system triggered.': '紧急停机系统已触发。',
  'est. cost': '预计成本',
  'est. value': '预计价值',
  'failure prob %': '故障概率（%）',
  'flushing active': '冲洗作业进行中',
  'froude no.': '弗劳德数',
  'green factory l3': '三级绿色工厂',
  'h-q curve': '扬程—流量曲线',
  'hot spot temp': '热点温度',
  'in transit': '运输中',
  'incident triggered. pressure loss.': '事故工况已触发：压力下降。',
  'laser master': '激光基准仪',
  'main substation': '主变电站',
  'major replacement': '重大更换项目',
  'millimeter wave': '毫米波',
  'mql conversion': '市场认可线索转化率',
  'native tree planting': '乡土树种种植',
  'navigable depth': '通航水深',
  'next directive': '下一步指令',
  'oil cleanliness': '油液清洁度',
  'original value': '原值',
  'pause sim': '暂停仿真',
  'phase space trajectory': '相空间轨迹',
  'pore pressure': '孔隙水压力',
  'power draw': '输入功率',
  'precision blasting control': '精准爆破控制',
  'pressure drop': '压降',
  'pressure sudden rise +15%.': '压力突然上升15%。',
  'pulp density': '矿浆浓度',
  'radar magnetron kit': '雷达磁控管套件',
  'rail clamps': '夹轨器',
  'real-time price': '实时电价',
  'reheat temp': '再热温度',
  'repair cost': '维修成本',
  'replace limit': '更换限值',
  'reservoir level': '库水位',
  'reset defaults': '恢复默认值',
  'risk prob.': '风险概率',
  'safety training video': '安全培训视频',
  'safety valve actuation command sent.': '安全阀动作指令已下发。',
  'sag mill testing standards': '半自磨机试验标准',
  'save snapshot': '保存快照',
  'search company...': '搜索企业…',
  'search customer...': '搜索客户…',
  'case #2201: rotor imbalance': '案例 #2201：转子不平衡',
  'marine-kinetic-dynamics engine v3.4 - deck machinery shield active': '船舶动力学引擎 v3.4—甲板机械预测防护已启用',
  'msa china 2024': '中国海事局2024',
  'rotterdam rwg': '鹿特丹RWG码头',
  'search entity...': '搜索企业主体…',
  'senior propulsion engineer': '高级推进系统工程师',
  'shanghai yangshan iv': '上海洋山四期码头',
  'site engineer': '现场工程师',
  'sla countdown': '服务时限倒计时',
  'solenoid valve': '电磁阀',
  'solve time': '求解耗时',
  'specific consumption': '单位消耗',
  'stability (fos)': '稳定安全系数（FoS）',
  'start sim': '开始仿真',
  'start/stop freq': '启停频次',
  'steam force induced vibration': '蒸汽激振',
  'synergy index': '协同指数',
  'system uptime': '系统连续运行时间',
  'tech pioneer': '技术先行客户',
  'thermal cycling': '热循环',
  'threat level': '威胁等级',
  'time elapsed': '已用时间',
  'top spender': '高价值客户',
  'total contract value': '合同总额',
  'troubleshooting guide': '故障排查指南',
  'turbine oil whip during startup': '汽轮机启动过程油膜振荡',
  'type instruction...': '请输入操作指令…',
  'typical failure library': '典型故障库',
  'ultrasonic array': '超声阵列',
  'valve actuation fail.': '阀门动作失败。',
  'valve position': '阀位',
  'vibration sensor #2 spike > 5mm/s.': '2号振动传感器测值突升至5 mm/s以上。',
  'vs last month': '较上月',
  'war-mode active': '应急模式已启用',
  'water body': '水体',
  'wind dir': '风向',
  'wind spd': '风速',
  'wire transfer #9921': '银行转账 #9921',
  'zpmc-smart-structure core v3.0 - active': '振华重工智能结构分析核心 v3.0—运行中',
  '_ awaiting simulation data...': '正在等待仿真数据…',
  '_ waiting for sign-off...': '正在等待签署确认…',
  '-- end of stream --': '——数据流结束——',
  '-- receiving stream --': '——正在接收数据流——',
  '[10:15:00] shift change complete': '[10:15:00] 交接班完成',
  '[10:42:05] alert: fire detected at hub node 0!': '[10:42:05] 告警：0号枢纽节点发现火情！',
  '[10:42:06] auto: evacuation alarm broadcast': '[10:42:06] 自动处置：已广播疏散警报',
  '[10:42:06] auto: ventilation reversed': '[10:42:06] 自动处置：通风系统已反向运行',
  '[10:42:15] comms: team a ack receipt': '[10:42:15] 通信：A组已确认收到指令',
  '[10:43:00] sensor: high co in deep sump': '[10:43:00] 传感器：深部集水坑一氧化碳浓度偏高',
  '[10:45:05] data: baseline calculation started...': '[10:45:05] 数据：已开始基准计算…',
  '[10:45:08] check: piezometer p-102 offset': '[10:45:08] 检查：渗压计 P-102 存在偏移',
  '[10:45:12] net: uplink established to scada.': '[10:45:12] 网络：已连接监控与数据采集系统。',
  '[auth] fingerprint verified...': '[认证] 特征指纹验证通过…',
  '[data] mapping old sn performance...': '[数据] 正在关联原序列号性能记录…',
  '[info] target: v3.0 upgraded version...': '[信息] 目标版本：v3.0…',
  '[wait] awaiting hardware link...': '[等待] 正在等待硬件连接…',
  '% data loaded': '数据加载比例',
  '% life used': '寿命消耗比例',
  '• detailed report available': '• 可查看详细报告',
  '+ add account': '+ 添加账户',
  '+ add action item': '+ 添加处置事项',
  '0 active defects': '0项活动缺陷',
  '1 environmental cert missing.': '缺少1项环境认证。',
  '1 permit expiring in 15 days.': '有1项许可证将在15天后到期。',
  '1x amplitude is within normal range.': '一倍频幅值处于正常范围。',
  '1x amplitude sudden rise': '一倍频幅值突升',
  '2x and 3x harmonics present but weak.': '存在二倍频和三倍频谐波，但幅值较弱。',
  '3 berths active': '3个泊位正在作业',
  '3 days left': '剩余3天',
  '3d bathymetry': '三维水深地形',
  '3d context': '三维场景',
  '3d digital twin - fan coil unit': '三维数字孪生—风机盘管机组',
  '3d digital twin - fire pump set': '三维数字孪生—消防泵组',
  '3d digital twin - high mast structure': '三维数字孪生—高杆灯结构',
  '3d digital twin - shafting system': '三维数字孪生—轴系系统',
  '3d digital twin - windlass system': '三维数字孪生—锚机系统',
  '3d explode': '三维分解视图',
  '3d models': '三维模型',
  '3d models (step/ifc)': '三维模型（STEP/IFC）',
  '3d reconstruction active': '三维重建进行中',
  '3d rope vision analysis': '钢丝绳三维视觉分析',
  '3rd party audit': '第三方审计',
  '450 days safe ops': '安全运行450天',
  '2x (misalignment)': '二倍频（不对中）',
  'absorbed energy:': '吸收能量：',
  'actual prod': '实际产量',
  'adjustment mode': '调整模式',
  'aggregate processing unit': '骨料加工单元',
  'ai vision analysis': '智能视觉分析',
  'aids to navigation (aton)': '航标助航系统（AtoN）',
  'aligning to wind vector...': '正在对准风向…',
  'angular velocity': '角速度',
  'anti-collision radar': '防碰撞雷达',
  'apparent wind': '视风',
  'approach angle': '靠泊角度',
  'ballast tank levels': '压载舱液位',
  'battery bank': '蓄电池组',
  'bit depth': '钻头深度',
  'brg temp': '轴承温度',
  'cargo holds temp': '货舱温度',
  'chainage (distance)': '里程',
  'channel a: hall sensor raw': 'A通道：霍尔传感器原始值',
  'color anomaly': '色度异常',
  'conc. grade (cu)': '铜精矿品位',
  'current css (mm)': '当前闭边排料口（CSS，mm）',
  'current face': '当前掌子面',
  'daily permit check': '每日排放许可核验',
  'diff pressure (δp)': '压差（ΔP）',
  'download full report': '下载完整报告',
  'electrical subsystem': '电气子系统',
  'environmental protection': '环境保护',
  'est. run: 14 days': '预计续航14天',
  'froth depth': '泡沫层厚度',
  'froth vision analysis': '泡沫视觉分析',
  'gale warning in sector b4. course correction advised +5°.': 'B4区大风预警，建议航向修正5°。',
  'gamma (api)': '伽马射线（API）',
  'gas sensor (ch4)': '甲烷传感器（CH4）',
  'gearbox hss': '齿轮箱高速轴',
  'generator de': '发电机驱动端',
  'generator winding': '发电机绕组',
  'gnss coordinates': '卫星定位坐标',
  'grease system': '润滑脂系统',
  'heave (vertical)': '垂荡（垂直方向）',
  'heavy lifting operations': '重型起重作业',
  'high vibration detect': '检测到振动偏高',
  'hrs run: 48.5h': '累计运行48.5 h',
  'hydroset pressure': '液压调节系统压力',
  'icing load': '覆冰载荷',
  'inlet pressure': '进口压力',
  'instantaneous revenue:': '瞬时收益：',
  'insulator leaking current:': '绝缘子泄漏电流：',
  'intake pool': '进水池',
  'laser sensors: acquiring': '激光传感器：采集中',
  'last position fix': '最近定位',
  'last survey': '最近一次测量',
  'load moment': '载荷力矩',
  'main header': '出水总管',
  'mantle wear': '动锥衬板磨损',
  'mass pull': '精矿产率',
  'match 98.2% (standard industrial effluent)': '匹配度98.2%（标准工业废水）',
  'max tilt': '最大倾角',
  'microphone array gain: +12db': '麦克风阵列增益：+12 dB',
  'mineral flotation circuit': '矿物浮选回路',
  'mode: rotary drilling': '模式：旋转钻进',
  'mppt active': '最大功率点跟踪运行中',
  'nacelle yaw': '机舱偏航',
  'next 100m': '前方100米',
  'not detected': '未检出',
  'ocean logistics & operations': '海洋物流与船舶运营',
  'outlet pressure': '出口压力',
  'overload warning': '过载预警',
  'overspeed trip': '超速跳闸',
  'particle size': '粒度',
  'peak-peak y': 'Y向峰峰值',
  'permitted limit': '许可限值',
  'powder content (&lt;0.075)': '石粉含量（粒径小于0.075 mm）',
  'real-time logs': '实时日志',
  'renewable energy': '可再生能源',
  'reset latch': '复位锁存',
  'rop (speed)': '机械钻速（ROP）',
  'rotary speed': '旋转速度',
  'rotational freq': '转频',
  'screw conveyor speed': '螺旋输送机转速',
  'section s4-15: galloping detected': 'S4-15区段：检测到导线舞动',
  'segment erector': '管片拼装机',
  'sensor 2 (battery comp) - 10:42 am': '2号传感器（电池舱）—10:42',
  'shape index': '粒形指数',
  'shield tunneling system': '盾构掘进系统',
  'sig. wave height': '有效波高',
  'sog (speed)': '对地航速（SOG）',
  'solar charging profile (24h)': '近24小时太阳能充电曲线',
  'specific energy consumption': '单位能耗',
  'standard (zone ii)': 'II区级配标准',
  'standpipe pressure': '立管压力',
  'status: lifting': '状态：起吊中',
  'strata profile': '地层剖面',
  'surface oil sheen': '水面油膜',
  'task: line l4-s2': '任务：L4-S2线路',
  'tip speed: 72 m/s': '转子线速度：72 m/s',
  'total hook load': '大钩总载荷',
  'trip setpoint (110%)': '跳闸设定值（110%）',
  'type: pdc 8-blade': '类型：PDC八翼钻头',
  'ultra-high voltage grid / uhv-ac': '特高压电网 / 交流特高压',
  'used capacity': '已用容量',
  'uv-vis spectroscopy': '紫外-可见光谱分析',
  'vertical (y)': '垂直方向（Y）',
  'vertical shaft impact crusher (vsi)': '立轴冲击式破碎机（VSI）',
  'vibration x/y': 'X/Y向振动',
  'visual inspection: minor wear detected at drum end.': '目视巡检：卷筒端部发现轻微磨损。',
  'warning: transition zone detected at k1+260. recommended thrust reduction.': '预警：K1+260处检测到地层过渡带，建议降低推力。',
  'watch circle status': '位置警戒圈状态',
  'wob (weight on bit)': '钻压（WOB）',
  'y (hoist)': 'Y（起升）',
  'yaw rate': '偏航角速度',
  'ok': '正常',
  'clear': '无异常',
  'good': '良好',
  'mixed ground': '软硬复合地层',
  'soft soil': '软土地层',
  '% passing': '累计筛下率（%）',
  '% solids': '固体质量分数（%）',
  '0s ago': '刚刚',
  '1x (unbalance)': '一倍频（不平衡）',
  'abs': '吸光度',
  'aft': '艉部',
  'alkaline': '碱性',
  'alongside': '已靠妥',
  'altitude': '海拔高度',
  'anchor': '锚泊',
  'anemometer': '风速仪',
  'auto-generated': '自动生成',
  'auto-wear': '磨损自动补偿',
  'autopilot: engaged': '自动舵：已投入',
  'bubble sz:': '气泡尺寸：',
  'cog (heading)': '对地航向（COG）',
  'color:': '颜色：',
  'compression': '压缩量',
  'cubical': '粒形方正',
  'cutterhead': '刀盘',
  'deep earth exploration': '深地勘探',
  'easting': '东坐标',
  'est: 450h left': '预计剩余450小时',
  'est. replace: 6mo': '预计6个月后更换',
  'fill percentage': '充填率',
  'fineness modulus': '细度模数',
  'floatables': '漂浮物',
  'fore': '艏部',
  'frother (mibc)': '起泡剂（MIBC）',
  'gamma ray': '伽马射线',
  'hard rock': '硬岩',
  'hard rock (iii)': 'Ⅲ级硬岩',
  'hook position': '吊钩位置',
  'ideal': '理想值',
  'installed: 2023-01': '安装时间：2023-01',
  'keyphasor: locked': '键相信号：已锁定',
  'knots': '节',
  'latitude': '纬度',
  'light availability': '灯器可用率',
  'lime (ph mod)': '石灰（pH调节剂）',
  'longitude': '经度',
  'none': '无',
  'northing': '北坐标',
  'p80 size': 'P80粒度',
  'parallelism': '平行度',
  'porosity (φ)': '孔隙度（Φ）',
  'position': '位置',
  'radius': '工作幅度',
  'real-time': '实时',
  'resistivity (ωm)': '电阻率（Ω·m）',
  'roll': '横摇',
  'roll:': '横滚角：',
  'sand equivalent': '砂当量',
  'special mark': '专用标',
  'stop': '停止',
  'suction manifold': '吸水总管',
  'teeth count:': '齿数：',
  'throughput (tph)': '处理量（t/h）',
  'trim:': '纵倾：',
  'true heading': '真航向',
  'up': '上行',
  'viscosity': '黏度',
  'wavelength (nm)': '波长（nm）',
  'yesterday - 08:00 am': '昨天 08:00',
  'x (trly)': 'X（小车）',
  'xanthate (pax)': '黄药（PAX）',
  'z (gntr)': 'Z（门架）',
  'e': '东',
  'azi': '方位角（AZI）',
  'inc': '井斜角（INC）',
  'tvd': '真垂深（TVD）',
  'rssi': '接收信号强度（RSSI）',
  'fm': '细度模数（FM）',
  'flo:': '流量：',
  'tmp:': '温度：',
  'pf:': '功率因数：',
  'swl': '安全工作载荷（SWL）',
  'connector type-a #': 'A型连接器编号',
  'thd-u 1.15%': '电压总谐波畸变率（THD-U）1.15%',
  'uab (kv)': 'Uab线电压（kV）',
  'ubc (kv)': 'Ubc线电压（kV）',
  'uca (kv)': 'Uca线电压（kV）',
  '2. 选择本地 excel 数据文件': '2. 选择本地Excel数据文件',
  '有功功率 output': '有功功率',
  'active / 投入': '已投入',
  'ai 智能诊断核心': '智能诊断核心',
  'auto / 自动': '自动',
  'live feed / 实时接入': '实时数据接入',
  'system id / 系统编号': '系统编号',
  'cam-04 (tower #12)': 'CAM-04（12号塔）',
  '点击选择数据表文件 (.xls)，支持同时选择多文件': '点击选择数据表文件（.xls），支持同时选择多个文件',
  '燃油效率分析（转速 vs 油耗）': '燃油效率分析（转速与油耗）',
  'ai核心模块a-7报告：': '智能诊断核心模块A-7报告：',
  'avr 状态': '自动电压调节器（AVR）状态',
  'pss (电力系统稳定器)': '电力系统稳定器（PSS）',
  'bio-reactors & purification': '生物反应与深度净化',
  'aeration blower a': 'A号曝气鼓风机',
  'aeration blower b': 'B号曝气鼓风机',
  'return pump a': 'A号污泥回流泵',
  'anoxic mixer': '缺氧池搅拌器',
  'average removal efficiency': '平均去除率',
  'avg removal eff': '平均去除率',
  'influent (进水)': '进水浓度',
  'effluent (出水)': '出水浓度',
  'limit (标准)': '排放限值',
  'sludge vol (svi)': '污泥体积指数（SVI）',
  'aeration tank do control': '曝气池溶解氧控制',
  'bio-process active': '生化处理运行中',
  'do vs airflow': '溶解氧与曝气量对比',
  'normal': '正常',
  'standby': '待机',
  'organization management': '组织关系管理',
  'view mode:': '视图模式：',
  'regions': '区域总部',
  'companies': '下属公司',
  'depts': '业务部门',
  'structure version': '组织架构版本',
  'timeline': '架构沿革',
  'now': '当前',
  'subsidiary': '子公司',
  'active': '正常经营',
  'dormant': '已停业',
  'legal rep': '法定代表人',
  'reg. capital': '注册资本',
  'founded': '成立日期',
  'address': '注册地址',
  'root': '集团总部',
  'region': '区域总部',
  'company': '公司',
  'dept': '部门',
  'entity details': '企业详情',
  'parent co': '母公司',
  'public float': '社会公众股',
  'founders': '创始人持股',
  'institutions': '机构持股',
  'n/a': '暂无',
  'payload': '载荷',
  'armature current': '电枢电流',
  'stator temp': '定子温度',
  'view details': '查看详情',
  'more actions': '更多操作',
  'ai diagnostics': '智能诊断',
  'nacelle vibration': '机舱振动',
  'spectrum analysis': '频谱分析',
  'real-time vibration trend': '实时振动趋势',
  'waveform analysis': '波形分析',
  'stability diagnosis': '稳定性诊断',
  'wear diagnosis': '磨损诊断',
  'structural vibration': '结构振动',
  'tension (kn)': '张力（kN）',
  'active monitoring': '持续监测中',
  'active monitoring status': '持续监测中',
  'system operational': '系统运行正常',
  'operational': '运行正常',
  'excellent': '优秀',
  'optimal': '最佳',
  'live': '实时',
  'recording': '正在录像',
  'loading...': '正在加载…',
  'search...': '请输入搜索内容',
  'ai reasoning': '智能研判',
  'ai inference': '智能推断',
  'ai advisory': '智能建议',
  'ai insights': '智能洞察',
  'ai insight': '智能洞察',
  'ai forecast': '智能预测',
  'ai model': '智能模型',
  'stream': '数据流',
  'real-time': '实时数据',
  'actions': '操作建议',
  'action': '处置建议',
  'action plan': '处置方案',
  'maintenance': '检修管理',
  'assets': '资产清单',
  'data stream': '实时数据流',
  'ai_advisory': '智能建议',
  'metrics': '核心指标',
  'core metrics': '核心指标',
  '24h': '近24小时',
  'trend': '趋势',
  'simulation': '仿真',
  'lifecycle': '全生命周期',
  'assessment': '综合评估',
  'score': '综合评分',
  'root cause': '根因分析',
  'resources': '资源配置',
  'distribution': '分布情况',
  'checklist': '检查清单',
  'status': '运行状态',
  'forecast': '趋势预测',
  'logs': '运行日志',
  'log': '运行日志',
  'prognostics': '趋势预测',
  'history': '历史记录',
  'efficiency': '运行效率',
  'archive': '业务档案',
  'workflow': '处置流程',
  'correlation': '关联分析',
  'minutes': '分钟',
  'telemetry': '遥测数据',
  'interactive': '交互视图',
  'o&m plan': '运维计划',
  'o&m history': '运维记录',
  'o&m': '运维',
  'specs': '技术参数',
  'live feed': '实时数据',
  'database': '数据库',
  'compliance': '合规检查',
  'sop': '标准作业程序',
  'taxonomy': '分类体系',
  'stats': '统计分析',
  'logistics': '物流管理',
  'logistics_stream': '物流数据流',
  'inputs': '输入参数',
  'input': '输入参数',
  'guide': '操作指南',
  'analysis': '分析',
  'risk radar': '风险雷达',
  'risk_radar': '风险雷达',
  'online': '在线',
  'standards': '标准规范',
  'oscilloscope': '波形监测',
  'inventory': '库存信息',
  'insights': '分析结论',
  'impact matrix': '影响矩阵',
  'optimization': '优化方案',
  'kpi radar': '绩效雷达',
  'regulatory': '法规要求',
  'specifications': '技术规格',
  'library': '资料库',
  'diagnosis': '诊断分析',
  'schedule': '计划安排',
  'pareto': '帕累托分析',
  'gantt view': '甘特图',
  'hierarchy': '层级关系',
  'fft analysis': '频谱分析',
  'events': '事件记录',
  'details': '详细信息',
  'radar': '雷达图',
  'strategy': '策略方案',
  'vibration trend': '振动趋势',
  'audit': '审核记录',
  'audit trail': '审计追踪',
  'audit_trail': '审计追踪',
  'sequence': '作业流程',
  'composition': '构成分析',
  'lubrication': '润滑状态',
  'evaluation': '评估结果',
  'queue': '待办队列',
  'decision log': '决策记录',
  'performance': '性能表现',
  'multi-dimensional': '多维分析',
  'tasks': '任务清单',
  'zones': '区域分布',
  'prediction': '预测结果',
  'sensitivity': '敏感性分析',
  'scorecard': '评分卡',
  'components': '部件清单',
  'throughput': '吞吐能力',
  'vulnerability': '薄弱环节',
  'health radar': '健康雷达',
  'troubleshooting': '故障排查',
  'historical trend': '历史趋势',
  'hydraulics': '液压系统',
  'voting': '评审投票',
  'tools': '工具清单',
  'deviation': '偏差分析',
  'environmental': '环境指标',
  'fingerprint': '特征指纹',
  'hydrograph': '水文过程线',
  'impact analysis': '影响分析',
  'comparison': '对比分析',
  'consumption': '消耗分析',
  'auto': '自动',
  'index': '综合指数',
  'efficiency decay': '效率衰减',
  'decision support': '决策支持',
  'integrity': '完整性评估',
  'benchmarking': '对标分析',
  'vib spectrum': '振动频谱',
  'savings': '节约量',
  'traceability': '全过程追溯',
  'balance': '平衡状态',
  'motor health': '电机健康状态',
  'roi': '投资回报率',
  'efficiency loss': '效率损失',
  'inflow': '入流情况',
  'thermal map': '温度分布图',
  'benchmark': '对标基准',
  'event log': '事件日志',
  'stability': '稳定性评估',
  'meteorology': '气象信息',
  'pending': '待处理',
  'thermal profile': '温度分布',
  'load trend': '负载趋势',
  'economy': '经济性分析',
  'download': '下载',
  'propagation': '传播路径',
  'reliability forecast': '可靠性预测',
  'gap analysis': '差距分析',
  'vibration spectrum': '振动频谱',
  'weibull distribution': '威布尔分布',
  'history cluster': '历史数据聚类',
  'analytics engine': '分析引擎',
  'constraints': '约束条件',
  'impact': '影响评估',
  'risk': '风险评估',
  'spectroscopy': '光谱分析',
  '24h forecast': '未来24小时预测',
  '24h trend': '近24小时趋势',
  '24h heat': '近24小时热状态',
  '24h load': '近24小时负载',
  '24h traffic': '近24小时流量',
  '48h forecast': '未来48小时预测',
  '6-month trend': '近6个月趋势',
  '8h window': '8小时统计窗口',
  '1.0s window': '1.0秒采样窗口',
  '100km range': '100 km 覆盖范围',
  'action impact energy': '动作冲击能量',
  'action items': '待办事项',
  'action required': '需要处理',
  'aeration uniformity': '曝气均匀度',
  'ai recommend': '智能建议',
  'asset coverage': '资产覆盖率',
  'asset handover': '资产移交',
  'ball mill digital twin': '球磨机数字孪生',
  'basic info': '基本信息',
  'battery / panto': '蓄电池 / 受电弓',
  'bearing gradient': '轴承温度梯度',
  'bearing trend (24h)': '轴承近24小时趋势',
  'case studies': '典型案例',
  'case study': '案例分析',
  'chain of custody': '全程保管记录',
  'clearance degradation': '间隙劣化趋势',
  'common causes': '共性原因',
  'complexity vs time': '复杂度与时间对比',
  'component list': '部件清单',
  'components audit': '部件审计',
  'compressor digital twin': '压缩机数字孪生',
  'cost breakdown': '成本构成',
  'criticality': '关键度评估',
  'cumulative damage (real data)': '累计损伤（实测数据）',
  'cutter vibration trend': '刀盘振动趋势',
  'cutting load distribution': '截割载荷分布',
  'dielectric response': '介电响应',
  'directional vib': '方向振动',
  'do vs airflow': '溶解氧与风量对比',
  'drain oil analysis': '回油分析',
  'dredger digital twin': '挖泥船数字孪生',
  'drive train': '传动链',
  'duration & pressure': '持续时间与压力',
  'early detection': '早期识别',
  'edge redundancy': '边缘节点冗余',
  'energy metabolism': '能量代谢',
  'equity & key persons': '股权结构与关键人员',
  'external risk': '外部风险',
  'fat / sat': '工厂验收测试 / 现场验收测试',
  'failure drivers': '故障诱因',
  'fea stress map': '有限元应力云图',
  'file formats': '文件格式',
  'fleet wide': '全船队',
  'following error': '跟随误差',
  'fouling rf factors': '污垢热阻影响因素',
  'fracture mech': '断裂力学',
  'frame load distribution': '机架载荷分布',
  'friction coeff': '摩擦系数',
  'gantry vibration trend': '门机振动趋势',
  'gap symmetry': '间隙对称性',
  'gear meshing': '齿轮啮合状态',
  'generation efficiency': '发电效率',
  'gnss position': '卫星定位',
  'heat dissipation': '散热状态',
  'historical cases': '历史案例',
  'hydrodynamic diagnosis': '水动力诊断',
  'real data': '实测数据',
  'control deck': '控制台',
  'facility req': '设施要求',
  'crest factor': '峰值因子',
  'combustion eff': '燃烧效率',
  'contribution matrix': '贡献度矩阵',
  'coupled risks': '耦合风险',
  'external fees': '外部费用',
  'green rating': '绿色评级',
  'hull perf': '船体性能',
  'prediction 24h': '未来24小时预测',
  '6-dof imu': '六自由度惯性测量',
  '6-dof monitor': '六自由度监测',
  '1x/2x dominant': '一倍频/二倍频占主导',
  'ch4 / co': '甲烷 / 一氧化碳',
  'csat / nps': '客户满意度 / 净推荐值',
  'nps / csat': '净推荐值 / 客户满意度',
  'eexi / cii': '现有船舶能效指数 / 碳强度指标',
  'fe & cu content': '铁、铜元素含量',
  'filter δp': '过滤器压差',
  'in vs out': '输入与输出对比',
  'inspection records': '巡检记录',
  'insulation res': '绝缘电阻',
  'iso/gb/gdpr': '国际标准 / 国家标准 / 数据保护规范',
  'last 1h': '近1小时',
  'lidar + optical': '激光雷达 + 光学检测',
  'life extension': '寿命延长评估',
  'magnetic field strength': '磁场强度',
  'maintenance advisory': '检修建议',
  'maintenance flow': '检修流程',
  'maintenance log': '检修记录',
  'mode comparison': '模式对比',
  'motors & drives': '电机与驱动装置',
  'moves per hour': '每小时作业次数',
  'nearby assets': '邻近资产',
  'online vs offline': '线上与线下对比',
  'operational zones': '作业区域',
  'opportunity cost': '机会成本',
  'overall performance': '综合性能',
  'overdue risk': '逾期风险',
  'pain points': '业务痛点',
  'paper insulation': '绝缘纸',
  'paris law': '帕里斯裂纹扩展定律',
  'particle type': '颗粒类型',
  'payment gateway': '支付网关',
  'phase a/b/c': 'A/B/C 三相',
  'planetary stage': '行星级',
  'pm schedule': '预防性检修计划',
  'pools & tanks': '水池与储罐',
  'quality ctrl': '质量控制',
  'quay crane digital twin': '岸桥数字孪生',
  'radar comparison': '雷达图对比',
  'rainflow count': '雨流计数',
  'rated speed': '额定转速',
  'real-time spectrogram': '实时频谱图',
  'regression analysis': '回归分析',
  'remote vs onsite': '远程与现场对比',
  'residual analysis': '残差分析',
  'resource concurrency': '资源并发情况',
  'ring gap (mm)': '环口间隙（mm）',
  'risk contagion': '风险传导',
  'risk zones': '风险区域',
  'rolling/sliding': '滚动 / 滑动',
  'safety fuse': '安全保护机制',
  'sag & gap matrix': '弧垂与间隙矩阵',
  'sat/5g': '卫星通信 / 第五代移动通信',
  'schema map': '数据模式映射',
  'scraping noise': '刮擦噪声',
  'screen performance': '筛分性能',
  'sea margin': '海况裕度',
  'seal health': '密封件健康度',
  'sealing health': '密封系统健康度',
  'metallurgy_genome': '冶金特征图谱',
  '24h_history': '近24小时历史记录',
  'bus-bar a/b': 'A/B 段母线',
  'circuit a': 'A 回路',
  'docs': '文档资料',
  'dpi': '图像分辨率',
  'electrochemical cp': '电化学阴极保护',
  'f80 / p80': '入料粒度 F80 / 排料粒度 P80',
  'fos': '安全系数',
  'h-v curve': '水头—库容曲线',
  'hf resonance': '高频共振',
  'hi trend': '健康指数趋势',
  'hole detail': '孔位详情',
  'id card': '身份档案',
  'iec 60599': 'IEC 60599 油中溶解气体诊断标准',
  'imdg classes': '国际海运危险货物分类',
  'key terms': '关键术语',
  'lhd dynamic twin': '铲运机动态孪生',
  'mm/yr': 'mm/年',
  'mph trend': '每小时作业次数趋势',
  'nlp analysis': '自然语言处理分析',
  'npsh trend': '净正吸入压头趋势',
  'nyquist plot': '奈奎斯特图',
  'o&m decisions': '运维决策',
  'o&m optimization': '运维优化',
  'o&m strategy': '运维策略',
  'o&m windows': '运维时间窗',
  'olpd monitoring': '在线局部放电监测',
  'on_hand': '现有库存',
  'op point': '运行工况点',
  'performance_track': '性能跟踪',
  'pms balancing': '电力管理系统负载平衡',
  'process tracker': '流程跟踪',
  'profinet': '工业以太网通信',
  'qoq trend': '环比趋势',
  'rack_01': '01号机架',
  'reliability eng': '可靠性工程',
  'rmr': '岩体质量等级',
  'roi_&_carbon': '投资回报与碳排放',
  'rps': '转/秒',
  'sadovsky': '萨道夫斯基公式',
  'se curve': '分离效率曲线',
  'segment traits': '分段特征',
  'ship ventilator digital twin': '船舶通风机数字孪生',
  'solar/batt': '光伏 / 蓄电池',
  'sr digital twin': '堆取料机数字孪生',
  'standard phrases': '标准用语',
  'strategy benchmark': '策略对标',
  'sts digital twin': '岸桥数字孪生',
  'submersion matrix': '浸没状态矩阵',
  'supplier_radar': '供应商雷达',
  'supply_resilience': '供应保障韧性',
  'survival analysis': '生存分析',
  'symptoms': '故障征兆',
  'synchroscope': '同步表',
  'synergy': '协同效应',
  'systemic risk': '系统性风险',
  'tactical_info': '处置策略信息',
  'tail/bend pulley': '尾部 / 改向滚筒',
  'tan delta': '介质损耗因数',
  'tan_delta': '介质损耗因数',
  'taxonomy_tree': '分类体系树',
  'tco model': '总拥有成本模型',
  'tco_optimization': '总拥有成本优化',
  'tear probability trend': '撕裂概率趋势',
  'templates': '模板',
  'temporal comparison': '时序对比',
  'teu/h': 'TEU/h',
  'threat matrix': '威胁矩阵',
  'thruster digital twin': '推进器数字孪生',
  'tidal window': '潮汐作业窗口',
  'tier_definition': '分级定义',
  'time horizon': '预测时域',
  'timing': '时序分析',
  'tolerance': '容差',
  'toolkit': '工具箱',
  'top experts': '重点专家',
  'topic radar': '主题雷达',
  'tornado chart': '龙卷风图',
  'torsional fft': '扭转振动频谱',
  'tph vs kw': '处理量（t/h）与功率（kW）对比',
  'transactions': '交易记录',
  'transcript': '文字记录',
  'transient_forensic': '瞬态事件溯源',
  'transit_hub': '运输枢纽',
  'transition vib trend': '过渡段振动趋势',
  'transmission line #42': '42号输电线路',
  'transverse load': '横向载荷',
  'trending': '趋势分析',
  'tribology': '摩擦学分析',
  'tribology_genome': '摩擦学特征图谱',
  'trigger_queue': '触发任务队列',
  'truck dynamic twin': '运输车辆动态孪生',
  'trust score': '可信度评分',
  'tube matrix': '管束矩阵',
  'tugboat digital twin': '拖轮数字孪生',
  'types': '类型',
  'uhf pd': '特高频局部放电',
  'unloader digital twin': '卸船机数字孪生',
  'up/down': '上行 / 下行',
  'validated': '已验证',
  'validator': '校验工具',
  'value_protected': '价值保障',
  'vendor_sla': '供应商服务等级',
  'vendors': '供应商',
  'vessel entry process': '船舶进港流程',
  'vessel taxonomy': '船舶分类体系',
  'vfd status': '变频器状态',
  'vhi trend': '振动健康指数趋势',
  'views trend': '浏览趋势',
  'violations': '违规项',
  'visibility': '可见性',
  'vision ai': '视觉智能分析',
  'vision_intel': '视觉智能分析',
  'visualizer': '可视化分析',
  'vital signs': '关键运行征兆',
  'vitals': '关键指标',
  'voice of customer': '客户之声',
  'voiceprint': '声纹特征',
  'volatility': '波动率',
  'vortex dynamics real-time twin': '涡流动力学实时孪生',
  'vulnerability rank': '薄弱项排序',
  'vulnerability_index': '薄弱项指数',
  'waf / dlp': '网络应用防火墙 / 数据防泄漏',
  'waste_matrix': '浪费项矩阵',
  'watch circle': '监控范围',
  'watch_circle_radar': '监控范围雷达',
  'watchlist': '重点关注清单',
  'water level (el.)': '水位（高程）',
  'waterfall analysis': '瀑布图分析',
  'wear debris': '磨损颗粒',
  'weld status': '焊缝状态',
  'why this?': '原因说明',
  'wms_sync': '仓储管理系统同步',
  'work orders': '作业工单',
  'work_metadata': '作业元数据',
  'workload': '工作负荷',
  'wqi metrics': '水质指数',
  'xrf analysis': 'X射线荧光分析',
  'xrf assay': 'X射线荧光化验',
  'yard utilization': '堆场利用率',
  'zone b': 'B 区',
  'd50 analysis': 'd50 粒径分析',
  'p vs s': 'P波与S波对比',
  't q': '转矩—流量特性',
  't-minus 4h': '倒计时4小时',
};

const PHRASES: Array<[string, string]> = [
  ['intelligent operation and maintenance platform', '智能运维平台'],
  ['industrial intelligent operation and maintenance', '工业智能运维'],
  ['industrial intelligent monitoring system', '工业智能监测系统'],
  ['industrial intelligent cockpit', '工业智能驾驶舱'],
  ['operations knowledge management', '运维知识管理'],
  ['predictive maintenance', '预测性维护'],
  ['digital twin', '数字孪生'],
  ['real-time monitoring', '实时监测'],
  ['real time monitoring', '实时监测'],
  ['real-time analysis', '实时分析'],
  ['real time analysis', '实时分析'],
  ['system operational', '系统运行正常'],
  ['system status: online', '系统状态：在线'],
  ['system status', '系统状态'],
  ['system online', '系统在线'],
  ['system active', '系统已启用'],
  ['active monitoring', '正在监测'],
  ['active status', '启用状态'],
  ['customer name', '客户名称'],
  ['unified code', '统一编码'],
  ['municipal transport bureau', '市交通运输局'],
  ['global logistics corp.', '环球物流公司'],
  ['quantum chip tech', '量子芯片科技'],
  ['rescue team alpha', 'A组救援队'],
  ['rescue team bravo', 'B组救援队'],
  ['medical unit', '医疗救援组'],
  ['triage tent', '检伤分类帐篷'],
  ['surface base', '地面基地'],
  ['tunnel main junction', '主隧道交汇处'],
  ['sensor calibration sop', '传感器标定标准作业程序'],
  ['slope stabilization a', 'A区边坡加固'],
  ['soil remediation b', 'B区土壤修复'],
  ['wetland construction', '湿地建设'],
  ['native tree planting', '乡土树种种植'],
  ['abnormal vibration', '振动异常'],
  ['within tol', '在允许偏差范围内'],
  ['handshake ok', '通信握手正常'],
  ['diff current', '差动电流'],
  ['blasting ops', '爆破作业'],
  ['hydrophilic waste', '亲水性废料'],
  ['hydrophobic ore', '疏水性矿石'],
  ['8d progress', '8D处置进度'],
  ['active pwr', '有功功率'],
  ['agv fleet', '无人搬运车队'],
  ['ai conf', '智能诊断置信度'],
  ['inner race', '轴承内圈'],
  ['air door', '风门'],
  ['algorithmic asset transfer', '算法资产移交'],
  ['alignment records', '对中记录'],
  ['annual churn', '年度客户流失率'],
  ['arm cylinder mount', '动臂油缸安装座'],
  ['asset circularity', '资产循环利用'],
  ['asset handover', '资产移交'],
  ['asset interchangeability', '资产互换性'],
  ['attained cii', '实际碳强度指标'],
  ['auxiliary o&m manual', '辅助系统运维手册'],
  ['avg hr', '平均心率'],
  ['avr output', '自动电压调节器输出'],
  ['bag load', '滤袋负载'],
  ['base stn', '基站'],
  ['baseline rul', '基准剩余寿命'],
  ['basic registration', '基础登记'],
  ['bearing node', '轴承节点'],
  ['best eff', '最佳效率'],
  ['bio-vision ai active', '生物视觉智能分析运行中'],
  ['biological protocol alpha', 'A类生物处理规程'],
  ['boolean check', '逻辑条件检查'],
  ['boom mid side', '动臂中段侧面'],
  ['boost pressure', '增压压力'],
  ['braking physics twin', '制动物理孪生'],
  ['breaking load', '破断载荷'],
  ['buffer stroke used', '缓冲器行程使用量'],
  ['bulk export', '批量导出'],
  ['cab rotation', '驾驶室旋转'],
  ['cabin safety space', '驾驶室安全空间'],
  ['cage velocity', '罐笼速度'],
  ['calculating physics model', '正在计算物理模型'],
  ['candidate set', '候选方案集'],
  ['capacity util', '容量利用率'],
  ['carbon neutrality', '碳中和'],
  ['cbd zone', '中央商务区'],
  ['charge per delay', '单段装药量'],
  ['check calendar', '查看日程'],
  ['chen senior', '陈高级工程师'],
  ['chief technology officer', '首席技术官'],
  ['chiller unit', '冷水机组'],
  ['lateral mark', '侧面标志'],
  ['clean coal', '精煤'],
  ['clean energy ratio', '清洁能源占比'],
  ['carbon monoxide', '一氧化碳'],
  ['co level', '一氧化碳浓度'],
  ['co max', '一氧化碳最高浓度'],
  ['co2 emission', '二氧化碳排放量'],
  ['co2 level', '二氧化碳浓度'],
  ['co₂ saved', '二氧化碳减排量'],
  ['coal shearer cutting unit gearbox 3d teardown', '采煤机截割部齿轮箱三维拆解'],
  ['coking coal', '焦煤'],
  ['cold region engineering', '寒区工程'],
  ['color temp', '色温'],
  ['command override', '指令强制接管'],
  ['commercial governance', '商务治理'],
  ['comp ratio', '压缩比'],
  ['component dna extraction active', '部件特征谱提取中'],
  ['component fab', '部件制造'],
  ['composite score', '综合评分'],
  ['concentrate grade', '精矿品位'],
  ['concrete durability', '混凝土耐久性'],
  ['cone crusher', '圆锥破碎机'],
  ['configure api gateway', '配置应用接口网关'],
  ['constraint config', '约束条件配置'],
  ['content hash', '内容哈希值'],
  ['control firmware update', '控制固件升级'],
  ['coolant temp', '冷却液温度'],
  ['corporate billing profile', '企业结算档案'],
  ['re-apply weight with ht glue', '使用耐高温胶重新粘接配重块'],
  ['cost minimized', '成本最低'],
  ['cover wear', '覆盖层磨损'],
  ['crack len', '裂纹长度'],
  ['crane productivity', '起重机作业效率'],
  ['critical evacuate', '危险：立即撤离'],
  ['critical fade', '严重热衰退'],
  ['critical maintenance directive', '重大维护指令'],
  ['criticality convergence field', '关键度收敛区'],
  ['csat score', '客户满意度评分'],
  ['current choice', '当前方案'],
  ['current countdown', '当前倒计时'],
  ['current cut-off grade', '当前边界品位'],
  ['current vel', '当前流速'],
  ['customer experience', '客户体验'],
  ['customer sat', '客户满意度'],
  ['cut point', '分级粒度'],
  ['cyclone pressure', '旋流器压力'],
  ['cold cylinder', '冷缸'],
  ['cylinder liner diameter', '气缸套直径'],
  ['damaged seal', '密封件损坏'],
  ['danger zone', '危险区域'],
  ['data entry complete', '数据录入完成'],
  ['data gap', '数据缺口'],
  ['data lake archiver', '数据湖归档程序'],
  ['data maturity', '数据成熟度'],
  ['data steward', '数据管理员'],
  ['dead lvl', '死水位'],
  ['decarbonization compliance', '脱碳合规'],
  ['deep sump', '深部集水池'],
  ['defect contam', '缺陷：污染'],
  ['defect deform', '缺陷：变形'],
  ['red indicates critical failure path', '红色表示严重故障路径'],
  ['adhesion failure due to high operating temp', '运行温度过高导致粘接失效'],
  ['against sliding', '抗滑稳定'],
  ['alignai v2.4 active', 'AlignAI 对中分析系统运行中'],
  ['asset handover & startup', '资产移交与投运'],
  ['authorized field tech', '授权现场技术人员'],
  ['autonomy', '续航能力'],
  ['cooling tower optimization', '冷却塔优化'],
  ['lubrication degrading', '润滑状态下降'],
  ['clean coal product', '精煤产品'],
  ['evacuation route calculated', '疏散路线已生成'],
  ['sent to hud', '已发送至抬头显示设备'],
  ['component fab taiwan', '部件制造（中国台湾）'],
  ['freeze/thaw', '冻融'],
  ['conv. surface', '对流边界面'],
  ['critical (evacuate)', '危险（立即撤离）'],
  ['cyl #5', '5号气缸'],
  ['misfire', '失火'],
  ['daily co₂', '每日二氧化碳排放量'],
  ['corrected via interpolation', '已通过插值修正'],
  ['deepscan ai v4.2 active', 'DeepScan 智能检测系统运行中'],
  ['defect flashover', '缺陷：闪络'],
  ['deposition rate', '沉积速率'],
  ['straight-line', '直线法'],
  ['invoice mismatches', '发票不匹配项'],
  ['insulated gloves', '绝缘手套'],
  ['planet gear', '行星轮'],
  ['detected: 3 signals', '检测到3个信号'],
  ['diagnosing asset', '正在诊断资产'],
  ['digital archive explorer', '数字档案浏览器'],
  ['digital twin state replay', '数字孪生状态回放'],
  ['digital watershed twin', '数字流域孪生'],
  ['disc temperature', '制动盘温度'],
  ['displaying real-time telemetry for', '正在显示以下对象的实时遥测数据：'],
  ['dist a west', 'A配电区（西区）'],
  ['dist b east', 'B配电区（东区）'],
  ['distance to go', '剩余航程'],
  ['dominant dir', '主导方向'],
  ['door #4 leak', '4号风门泄漏'],
  ['dr. wang level 5', '王博士（五级专家）'],
  ['dr. zhang chief', '张博士（首席专家）'],
  ['dr. zhang lead', '张博士（负责人）'],
  ['dr. zhang is annotating', '张博士正在标注'],
  ['ar annotation', '增强现实标注'],
  ['drawing no', '图纸编号'],
  ['drawings', '图纸'],
  ['drive temp warn', '驱动系统温度告警'],
  ['drone unit', '无人机组'],
  ['dump elevation', '卸载标高'],
  ['dust spr', '喷雾抑尘'],
  ['dwell pick', '取货停留时间'],
  ['dynamic equilibrium tracker', '动态平衡跟踪'],
  ['dynamic lp', '动态线性规划'],
  ['effective rate', '有效率'],
  ['efficiency loss under-trucked', '车辆不足造成的效率损失'],
  ['electrical diagnostician', '电气诊断专家'],
  ['electrical spec', '电气规范'],
  ['electricity price', '电价'],
  ['electro-hydraulic servo valve diagnostics', '电液伺服阀诊断'],
  ['emergency notification', '紧急通知'],
  ['emergency protocol alpha', 'A级应急处置规程'],
  ['empty slot', '空闲时段'],
  ['en route', '途中'],
  ['enable slicer', '启用切片器'],
  ['encrypted media session', '加密媒体会话'],
  ['encrypting assets', '正在加密资产'],
  ['energy / move', '单次作业能耗'],
  ['energy reversion cycle', '能量回收循环'],
  ['energy storage & arbitrage', '储能与峰谷套利'],
  ['engine service manual', '发动机维修手册'],
  ['enter remote command', '请输入远程指令'],
  ['enterprise / gov / ind', '企业 / 政府机构 / 个人'],
  ['equipment deployed', '已部署设备'],
  ['equipment types', '设备类型'],
  ['errors detected', '检测到错误'],
  ['est. annual saving', '预计年度节省金额'],
  ['est. mileage left', '预计剩余里程'],
  ['est. yield', '预计产量'],
  ['pilot on board', '引航员已登船'],
  ['excitation system carbon brush online replacement', '励磁系统碳刷在线更换'],
  ['exhaust plume', '排气烟羽'],
  ['explosion factor', '爆炸系数'],
  ['extended drive train', '延保传动系统'],
  ['extension potential', '延寿潜力'],
  ['external api client', '外部应用接口客户端'],
  ['face air', '工作面风量'],
  ['failure mode identification', '故障模式识别'],
  ['fatigue striation', '疲劳条纹'],
  ['fault title', '故障标题'],
  ['feature used', '使用的功能'],
  ['feedwater pump', '给水泵'],
  ['ferrous debris accumulation rate', '铁磁性磨屑累积速率'],
  ['filling/emptying', '充水/泄水'],
  ['final commissioning report signature pending', '最终调试报告待签署'],
  ['finite element stress twin', '有限元应力孪生'],
  ['first come first serve', '先到先服务'],
  ['fixed route', '固定路线'],
  ['fleet rul average', '车队平均剩余寿命'],
  ['flood ctrl', '防洪控制'],
  ['flood defense command', '防洪调度指挥'],
  ['flood lvl', '防洪限制水位'],
  ['flood prev', '防洪'],
  ['flow direction', '流向'],
  ['fragmentation quality index', '爆破块度质量指数'],
  ['francis turbine', '混流式水轮机'],
  ['front suspension', '前悬架'],
  ['frozen wall status', '冻结壁状态'],
  ['fuel cons', '燃料消耗量'],
  ['fully productive', '完全有效生产'],
  ['fwd stern tube', '艏轴管'],
  ['g-force load', '过载载荷'],
  ['gate synchronization', '闸门同步'],
  ['generate label', '生成标签'],
  ['generate restock order', '生成补货单'],
  ['generating flow', '发电流量'],
  ['geo-hazard analysis', '地质灾害分析'],
  ['geotechnical risk monitor', '岩土工程风险监测'],
  ['gis circuit breaker mechanical characteristics testing', 'GIS断路器机械特性试验'],
  ['gis_signal strong', '卫星定位信号：强'],
  ['global administrator', '全局管理员'],
  ['global sanctions list', '全球制裁名单'],
  ['global shell co', '境外空壳公司'],
  ['global spare parts acceptance control', '全球备件验收控制'],
  ['global spare parts identity & standardization', '全球备件标识与标准化'],
  ['global threat level', '全局威胁等级'],
  ['golden batch ideal', '黄金批次（理想工况）'],
  ['goods received from factory', '已收到工厂发出的货物'],
  ['gov oil', '调速器油'],
  ['based on recent weather patterns', '根据近期天气变化规律'],
  ['could yield an additional', '预计还可增加'],
  ['detected high voltage proximity', '检测到临近高压带电区域'],
  ['ensure technician is wearing insulated gloves', '请确保技术人员佩戴绝缘手套'],
  ['use of ar annotation', '使用增强现实标注'],
  ['reduced resolution time by 30%', '将解决时长缩短了30%'],
  ['complex vibration cases', '复杂振动案例'],
  ['dso increased by 15% in last quarter', '上季度应收账款周转天数上升15%'],
  ['under-trucked', '运输车辆配置不足'],
  ['has unconnected vertices', '存在未连接顶点'],
  ['manifold check failed', '流形检查未通过'],
  ['engineer accepted the task via mobile app', '工程师已通过移动端接受任务'],
  ['wheat', '小麦'],
  ['requested structure blueprint', '请求查看结构图纸'],
  ['face 1301 coal', '1301采煤工作面'],
  ['filling/emptying is the critical path', '充水/泄水是关键路径'],
  ['fuel level', '燃油液位'],
  ['schedule refueling after current dump', '请在本次卸载后安排加油'],
  ['full access to all data and configurations', '可完全访问全部数据和配置'],
  ['gpu solver active', '图形处理器求解器运行中'],
  ['grade a suitable', 'A级：适用'],
  ['grade b+ compliant', 'B+级（合规）'],
  ['grid box retarder', '电阻栅箱（缓速器）'],
  ['grouping smaller vessels for next cycle', '正在为下一周期编组小型船舶'],
  ['guide vane shear pin failure handling drill', '导叶剪断销故障处置演练'],
  ['hami wind farm', '哈密风电场'],
  ['haul fuel eq', '运输等效燃油消耗'],
  ['hauling full', '满载运输'],
  ['heave max', '最大升沉'],
  ['heavy mach', '重型机械'],
  ['heidaigou open pit', '黑岱沟露天矿'],
  ['high demand for hydraulics exceeds current expert availability by 15%', '液压专业需求超出当前专家可用能力15%'],
  ['recommend cross-training or recruiting', '建议开展跨专业培训或招聘补充'],
  ['high frequency modulation detected around', '在以下频率附近检测到高频调制：'],
  ['risk contagion from parent entity', '来自母公司的风险传导'],
  ['high saturation levels indicate minimal infiltration capacity', '高饱和度表明下渗能力很低'],
  ['runoff coefficient estimated at', '估算径流系数为'],
  ['high turbidity indicates internal erosion', '高浑浊度表明可能存在内部侵蚀'],
  ['high value difficult but fast', '高价值（难度高、处理快）'],
  ['high voltage tester', '高压测试仪'],
  ['high-cycle fatigue due to flow-induced vibration', '流致振动引起的高周疲劳'],
  ['high-horsepower engine diagnostics', '大功率发动机诊断'],
  ['hoist up', '起升'],
  ['hourly prod', '小时产量'],
  ['hr avg', '平均心率'],
  ['hvac cooling loop', '暖通空调冷却回路'],
  ['hydraai v3.2 active', 'HydraAI 液压智能分析系统运行中'],
  ['hydraulic calculations', '液压计算书'],
  ['hydraulic roof support cylinder internal leakage simulation', '液压支架油缸内泄漏仿真'],
  ['hydraulics eng', '液压工程师'],
  ['hydro guide bearing temperature anomaly investigation', '水轮机导轴承温度异常排查'],
  ['hydro-cyclone simulation', '水力旋流器仿真'],
  ['hydro-dynamic simulation', '水动力仿真'],
  ['hydro-guard system', '水害防护系统'],
  ['hydro-navigation system', '水运导航系统'],
  ['hydro-power core asset assurance', '水电核心资产保障'],
  ['hydrologic anomaly field scan', '水文异常场扫描'],
  ['hydrological intelligence', '水文智能分析'],
  ['ice sheet', '冰盖'],
  ['identifying what matters most to customers', '识别客户最关注的因素'],
  ['identity verif', '身份核验'],
  ['immediate halt to prevent catastrophic failure', '立即停机以防止灾难性故障'],
  ['high production loss', '生产损失较高'],
  ['impact laboratory', '冲击试验室'],
  ['increase irrigation in zone-2 by 10%', '将2区灌溉量增加10%'],
  ['optimize grain filling stage', '优化灌浆期管理'],
  ['industrial brain', '工业智能中枢'],
  ['industrial problem center', '工业问题中心'],
  ['industrial spare parts trust-link protocol', '工业备件可信互联协议'],
  ['inflow/outflow', '入流/出流'],
  ['initial defects', '初始缺陷'],
  ['initial inspection confirms bearing wear on shaft 2', '初步检查确认2号轴承存在磨损'],
  ['requesting spare part', '正在申请备件'],
  ['initiate evacuation', '启动疏散'],
  ['initiate renewal workflow', '启动续期流程'],
  ['initiate replacement procedure', '启动更换流程'],
  ['inject road blockage', '设置道路阻断'],
  ['inlet butterfly valve hydraulic system repair', '进水蝶阀液压系统检修'],
  ['insulator visual', '绝缘子视觉检测'],
  ['intellectual property core', '知识产权核心'],
  ['interactive whiteboard active', '交互式白板已启用'],
  ['rotate to inspect layers', '旋转查看各层'],
  ['internal meeting', '内部会议'],
  ['inv. velocity', '反演速度'],
  ['isolation of servo valve hydraulic circuit followed by manual actuation test', '隔离伺服阀液压回路后进行手动动作试验'],
  ['if stuck, switch to redundant controller', '如发生卡滞，请切换至冗余控制器'],
  ['jet trajectory', '射流轨迹'],
  ['job id / loc', '任务编号 / 位置'],
  ['junior tech', '初级技术人员'],
  ['cfo resigned', '财务负责人离职'],
  ['squeal', '尖啸声'],
  ['knowledge base hit', '知识库命中率'],
  ['knowledge reuse', '知识复用'],
  ['lab testing bench', '实验室测试台'],
  ['labor availability', '人员可用率'],
  ['laser alignment kit', '激光对中工具包'],
  ['last reviewed', '最近复核时间'],
  ['latest sample', '最新样本'],
  ['moisture content trending up', '含水率呈上升趋势'],
  ['suggest vacuum filtration', '建议进行真空过滤'],
  ['launch test', '启动试验'],
  ['layer 1', '第1层'],
  ['layer height', '层高'],
  ['lead -> deal', '线索转商机'],
  ['legal lawsuits', '法律诉讼'],
  ['li engineer', '李工程师'],
  ['li tech', '李技术员'],
  ['life degradation hologram', '寿命劣化全息图'],
  ['lifecycle stages', '生命周期阶段'],
  ['waste mixed', '废料混入率'],
  ['link successful', '关联成功'],
  ['linked docs', '关联文档'],
  ['litigation history', '诉讼记录'],
  ['live updating', '实时更新中'],
  ['local port ord. sec', '当地港口条例第'],
  ['local server node', '本地服务器节点'],
  ['localized pitting detected on tooth surface', '齿面检测到局部点蚀'],
  ['risk of spalling within 300 hrs', '预计300小时内存在剥落风险'],
  ['verify hydraulic pressure release', '请确认液压压力已释放'],
  ['lockout/tagout', '上锁挂牌'],
  ['login mobile', '移动端登录'],
  ['logistics & parts requisition', '物流与备件申领'],
  ['lost energy', '损失电量'],
  ['low efficiency simple but slow', '低效率（操作简单但耗时较长）'],
  ['lower level', '下水库水位'],
  ['machine account for 3rd party integrations', '用于第三方集成的机器账户'],
  ['magnification', '放大倍数'],
  ['main canal', '总干渠'],
  ['main pres', '主管压力'],
  ['main transformer cooler cleaning procedure', '主变压器冷却器清洗作业规程'],
  ['maint. strategy', '维护策略'],
  ['maintenance submission portal', '维护申请门户'],
  ['major disagreement on', '主要分歧：'],
  ['maple logistics', '枫叶物流'],
  ['mapping fields', '正在映射字段'],
  ['maritime safety administration', '海事安全管理机构'],
  ['marketing automation', '营销自动化'],
  ['masking rule', '脱敏规则'],
  ['master data match', '主数据匹配'],
  ['material impurity leading to premature fatigue crack initiation', '材料杂质导致疲劳裂纹过早萌生'],
  ['material sets', '材料集'],
  ['max deflection', '最大挠度'],
  ['max principal stress', '最大主应力'],
  ['von mises', '冯·米塞斯'],
  ['max sub', '最大沉降量'],
  ['med risk', '中等风险'],
  ['mfl magnetic flux leakage audit', 'MFL漏磁检测'],
  ['micro-structure view', '微观结构视图'],
  ['mine hoist disc brake clearance tuning operation', '矿井提升机制动盘间隙调整作业'],
  ['mineral processing digital twin', '选矿数字孪生'],
  ['miners underground', '井下矿工人数'],
  ['mining elec', '采矿用电'],
  ['mining haul truck electric wheel assembly training', '矿用卡车电动轮组装培训'],
  ['minor correction', '轻微修正'],
  ['missing certificate', '缺少证书'],
  ['mission timer', '任务计时'],
  ['miter gate', '人字闸门'],
  ['mobile app', '移动应用'],
  ['moisture & et trend', '土壤含水率与蒸散量趋势'],
  ['mom retention', '环比留存率'],
  ['monitoring software', '监测软件'],
  ['monthly ops report', '月度运维报告'],
  ['most impactful', '影响最大'],
  ['multi-objective optimization', '多目标优化'],
  ['multi-party data exchange bus', '多方数据交换总线'],
  ['multimodal logistics hub', '多式联运枢纽'],
  ['named defendant in new contract dispute lawsuit', '在新增合同纠纷诉讼中被列为被告'],
  ['nansha logistics park', '南沙物流园'],
  ['navigable status open', '通航状态：开放'],
  ['net benefit', '净收益'],
  ['net book value', '账面净值'],
  ['net efficiency', '净效率'],
  ['life-cycle monitor', '全生命周期监测'],
  ['lifecycle monitor', '全生命周期监测'],
  ['hydraulic active', '液压系统运行中'],
  ['resonance monitor', '共振监测'],
  ['load balance active', '负载均衡运行中'],
  ['live analysis', '实时分析'],
  ['current pressure', '当前压力'],
  ['current depth', '当前深度'],
  ['current risk', '当前风险'],
  ['current status', '当前状态'],
  ['current value', '当前值'],
  ['current level', '当前等级'],
  ['system health', '系统健康度'],
  ['health score', '健康评分'],
  ['risk level', '风险等级'],
  ['risk score', '风险评分'],
  ['risk matrix', '风险矩阵'],
  ['critical risk', '重大风险'],
  ['high risk', '高风险'],
  ['medium risk', '中等风险'],
  ['low risk', '低风险'],
  ['normal status', '正常状态'],
  ['vessel status', '船舶状态'],
  ['load status', '负载状态'],
  ['operating status', '运行状态'],
  ['operation status', '运行状态'],
  ['maintenance status', '检修状态'],
  ['power output', '功率输出'],
  ['active power', '有功功率'],
  ['total power', '总功率'],
  ['total load', '总负载'],
  ['total energy', '总能量'],
  ['total stress', '总应力'],
  ['total seepage', '总渗流量'],
  ['wind speed', '风速'],
  ['wind direction', '风向'],
  ['rotor speed', '转子转速'],
  ['flow rate', '流量'],
  ['data stream', '数据流'],
  ['data throughput', '数据吞吐量'],
  ['daily treatment', '日处理量'],
  ['energy intensity', '能耗强度'],
  ['carbon footprint', '碳足迹'],
  ['return ratio', '回流比'],
  ['average level', '平均水位'],
  ['average speed', '平均速度'],
  ['average pressure', '平均压力'],
  ['maximum value', '最大值'],
  ['minimum value', '最小值'],
  ['max surge', '最大涌浪'],
  ['min surge', '最小涌浪'],
  ['target value', '目标值'],
  ['target pressure', '目标压力'],
  ['alert threshold', '告警阈值'],
  ['warning threshold', '预警阈值'],
  ['failure probability', '故障概率'],
  ['failure analysis', '故障分析'],
  ['fault diagnosis', '故障诊断'],
  ['diagnostic conclusion', '诊断结论'],
  ['diagnostic report', '诊断报告'],
  ['recommended action', '建议措施'],
  ['control measures', '控制措施'],
  ['root cause', '根本原因'],
  ['remaining useful life', '剩余使用寿命'],
  ['service life', '使用寿命'],
  ['days remaining', '剩余天数'],
  ['maintenance plan', '检修计划'],
  ['maintenance schedule', '检修安排'],
  ['maintenance cost', '检修成本'],
  ['inspection history', '巡检历史'],
  ['last inspection', '上次巡检'],
  ['last sync', '最近同步'],
  ['last update', '更新时间'],
  ['last updated', '更新时间'],
  ['updated:', '更新时间：'],
  ['component type', '部件类型'],
  ['component health', '部件健康度'],
  ['equipment health', '设备健康度'],
  ['asset health', '资产健康度'],
  ['structural integrity', '结构完整性'],
  ['thermal field', '温度场'],
  ['stress field', '应力场'],
  ['vibration analysis', '振动分析'],
  ['spectrum analysis', '频谱分析'],
  ['frequency analysis', '频率分析'],
  ['trend analysis', '趋势分析'],
  ['performance analysis', '性能分析'],
  ['efficiency analysis', '效率分析'],
  ['energy analysis', '能耗分析'],
  ['quality analysis', '质量分析'],
  ['safety analysis', '安全分析'],
  ['data analysis', '数据分析'],
  ['simulation analysis', '仿真分析'],
  ['real-time data', '实时数据'],
  ['historical data', '历史数据'],
  ['monitoring data', '监测数据'],
  ['sensor data', '传感器数据'],
  ['model data', '模型数据'],
  ['data quality', '数据质量'],
  ['data source', '数据源'],
  ['data link', '数据链路'],
  ['connection status', '连接状态'],
  ['network status', '网络状态'],
  ['secure connection', '安全连接'],
  ['encrypted connection', '加密连接'],
  ['connection established', '连接已建立'],
  ['synchronized', '已同步'],
  ['sync complete', '同步完成'],
  ['click and drag to rotate', '单击并拖动以旋转'],
  ['drag to rotate, scroll to zoom', '拖动旋转，滚轮缩放'],
  ['click pads to view details', '单击部件查看详情'],
  ['click nodes to inspect details', '单击节点查看详情'],
  ['no signal', '无信号'],
  ['no data', '暂无数据'],
  ['no records', '暂无记录'],
  ['loading...', '正在加载…'],
  ['loading', '正在加载'],
  ['operation successful', '操作已完成'],
  ['operation failed', '操作未完成'],
  ['error occurred', '发生错误'],
  ['try again', '重试'],
  ['reset view', '重置视角'],
  ['full screen', '全屏'],
  ['search...', '请输入搜索内容'],
  ['search', '搜索'],
  ['view details', '查看详情'],
  ['view report', '查看报告'],
  ['generate report', '生成报告'],
  ['download report', '下载报告'],
  ['export report', '导出报告'],
  ['export data', '导出数据'],
  ['save changes', '保存修改'],
  ['cancel', '取消'],
  ['confirm', '确认'],
  ['close', '关闭'],
  ['open', '打开'],
  ['start simulation', '开始仿真'],
  ['stop simulation', '停止仿真'],
  ['pause simulation', '暂停仿真'],
  ['simulation running', '仿真运行中'],
  ['digital twin active', '数字孪生运行中'],
  ['live digital twin', '实时数字孪生'],
  ['heavy rain alert', '暴雨告警'],
  ['secure / encrypted', '安全 / 已加密'],
  ['encrypted / wireless', '加密 / 无线连接'],
  ['fiber / realtime', '光纤 / 实时传输'],
  ['secure / plc-link', '安全 / 控制器连接'],
  ['port & terminal operations', '港口与码头作业'],
  ['knowledge network twin', '知识网络孪生'],
  ['physical interface topology', '物理接口拓扑'],
  ['environmental mitigation audit', '环境减排审计'],
  ['failure probability calculation', '故障概率计算'],
  ['thrust bearing film thickness dropping below critical threshold. schedule outage for oil injection pump check.', '推力轴承油膜厚度已降至严重阈值以下，请安排停机并检查注油泵。'],
  ['shaft runout exceeds safety margin', '轴系跳动量超过安全余量'],
  ['no articles found matching your criteria.', '未找到符合当前条件的内容。'],
  ['critical parameter thresholds', '关键参数阈值'],
  ['continuous transport system', '连续运输系统'],
  ['cylinder liner corrosion', '气缸套腐蚀'],
  ['emergency shutdown', '紧急停机'],
  ['working cycle curve', '工作循环曲线'],
  ['selected zone:', '选中区域：'],
  ['based on current component reliability data:', '基于当前部件可靠性数据：'],
  ['prediction space', '预测空间'],
  ['recommended actions', '建议措施'],
  ['control strategy', '控制策略'],
  ['system module:', '系统模块：'],
  ['module online', '模块在线'],
  ['recording', '录像中'],
  ['rec', '录像'],
];

const WORDS: Record<string, string> = {
  maintenance: '维护', 'real-time': '实时', intelligence: '智能', repair: '维修', delivery: '交付',
  ratio: '比率', throughput: '吞吐量', availability: '可用率', credit: '信用', customer: '客户',
  customers: '客户', static: '静态', engineering: '工程', generate: '生成', generated: '已生成',
  infrastructure: '基础设施', ops: '运维', procedure: '作业流程', shearer: '采煤机', tax: '税务',
  truck: '卡车', trucks: '卡车', usage: '使用率', axis: '轴', change: '变更', cleaning: '清洗',
  coeff: '系数', during: '期间', end: '结束', engineer: '工程师', ensure: '确保', entities: '主体',
  exposure: '暴露量', fail: '失败', handover: '移交', immediate: '立即', local: '本地', locked: '已锁定',
  panel: '面板', quantum: '量子', rear: '后部', rescue: '救援', resolution: '解决', shell: '壳体',
  shovel: '电铲', spillway: '溢洪道', update: '更新', via: '通过', wait: '等待', waiting: '等待中',
  apply: '应用', approve: '批准', bathymetry: '水深测量', bot: '智能助手', bottleneck: '瓶颈',
  clear: '清除', consultation: '会诊', correction: '修正', date: '日期', delay: '延迟', download: '下载',
  drop: '下降', element: '元素', enterprise: '企业客户', government: '政府机构', individual: '个人客户',
  entry: '条目', export: '导出', format: '格式', freeze: '冻结', haul: '运输', incident: '事件',
  increase: '增加', indicates: '表明', industrial: '工业', kinematic: '运动学', loc: '位置', lock: '锁定',
  lockout: '锁定', machine: '设备', mobile: '移动端', notice: '通知', pilot: '试点', pit: '矿坑',
  pitting: '点蚀', rain: '降雨', received: '已接收', reduced: '降低', replace: '更换', request: '申请',
  restoration: '恢复', road: '道路', rule: '规则', sample: '样本', saturation: '饱和度', sector: '区域',
  size: '规模', sorted: '已排序', start: '启动', sys: '系统', tactical: '战术', ticket: '工单',
  tilt: '倾斜', tooth: '轮齿', triggered: '已触发', tube: '管道', turnaround: '周转时间',
  underground: '井下', unified: '统一', ventilation: '通风', vessels: '船舶', virtual: '虚拟',
  waste: '废弃物', week: '周', yard: '堆场', reservoir: '水库', burst: '爆裂', medical: '医疗',
  triage: '检伤分类', tent: '帐篷', municipal: '市政', bureau: '管理局', overseas: '海外',
  est: '预计', call: '呼叫', ok: '正常', gen: '生成', hrs: '小时', pattern: '模式', account: '账户',
  automation: '自动化', cold: '低温', container: '集装箱', daily: '每日', ecological: '生态',
  loaded: '已加载', robot: '机器人', stop: '停止', warranty: '质保', abrasion: '磨蚀', address: '地址',
  adjust: '调整', advanced: '高级', ambient: '环境', amps: '安培', analyst: '分析人员', arrival: '到货',
  arrived: '已到达', assigned: '已分派', authorized: '已授权', automated: '自动化', avoided: '已避免',
  basin: '流域', batch: '批次', better: '更好', blocks: '区块', blueprint: '蓝图', body: '主体',
  brine: '盐水', buffer: '缓冲', buoy: '浮标', calculated: '计算值', camera: '摄像机', capture: '采集',
  chief: '负责人', circulation: '循环', cladding: '熔覆', click: '点击', closure: '关闭', cloud: '云端',
  coal: '煤炭', codes: '编码', comparison: '对比', completed: '已完成', complex: '复杂', concrete: '混凝土',
  construction: '建设', contract: '合同', coordinates: '坐标', count: '数量', created: '已创建',
  currently: '当前', debris: '碎屑', default: '默认', delays: '延误', deploy: '部署', description: '说明',
  detailed: '详细', docs: '文档', drainage: '排水', drivetrain: '传动系统', dump: '卸载', dwell: '停留时间',
  eco: '生态', edit: '编辑', electric: '电气', enable: '启用', engaged: '已投入', entering: '进入中',
  entity: '主体', erosion: '冲蚀', evacuation: '疏散', exchange: '交换', exploded: '分解', factory: '工厂',
  faults: '故障', feedback: '反馈', filling: '充填', final: '最终', financial: '财务', first: '首次',
  forensic: '取证', forensics: '取证分析', fully: '完全', future: '未来', gangue: '矸石', geological: '地质',
  gravity: '重力', hazard: '危险', healthy: '健康', highest: '最高', holographic: '全息', hotspot: '热点',
  hydropower: '水电', ice: '冰', inbound: '入库', increased: '已增加', increasing: '持续上升',
  indicating: '表明', infrared: '红外', initial: '初始', injector: '喷油器', inlet: '入口', inspect: '检查',
  install: '安装', instant: '即时', intake: '进水口', integrated: '集成', interface: '接口', invite: '邀请',
  irrigated: '已灌溉', irrigation: '灌溉', isolate: '隔离', issue: '问题', item: '事项', keywords: '关键词',
  lake: '湖区', leading: '前缘', leak: '泄漏', left: '左侧', levels: '等级', major: '主要', manager: '负责人',
  manuals: '手册', mean: '平均值', mesh: '网格', metal: '金属', minimal: '最低', mission: '任务',
  modulation: '调制', module: '模块', most: '最大', number: '编号', object: '对象', operator: '操作员',
  optimize: '优化', optimizer: '优化器', penstock: '压力钢管', permission: '权限', permit: '许可',
  pin: '销轴', pivot: '铰点', plant: '厂站', prevent: '预防', preventive: '预防性', primary: '主要',
  project: '项目', proposal: '方案', pumping: '抽水', quarter: '季度', ramp: '斜坡', record: '记录',
  recs: '建议', reduce: '降低', reducing: '正在降低', reference: '参考', registration: '登记', renewal: '更新',
  repository: '资料库', requests: '申请', requires: '需要', rise: '上升', river: '河道', roll: '横摇', route: '路线',
  runoff: '径流', save: '保存', saved: '已保存', savings: '节约', scheduled: '已安排', script: '脚本',
  sediment: '泥沙', seepage: '渗流', send: '发送', senior: '高级', severe: '严重', simulate: '仿真',
  slew: '回转', slope: '边坡', slow: '缓慢', soil: '土壤', solver: '求解器', space: '空间',
  specialist: '专家', spend: '支出', spike: '突升', stiction: '黏滞', strategic: '战略', stuck: '卡滞',
  success: '成功', suggested: '建议', suggests: '建议', sump: '集水池', synergy: '协同', tagout: '挂牌',
  tags: '标签', tailing: '尾矿', testing: '测试', token: '令牌', traceability: '可追溯性', track: '跟踪',
  traction: '牵引', transfer: '移交', tribology: '摩擦学', trigger: '触发', turning: '转向', turnover: '周转率',
  typhoon: '台风', unplanned: '计划外', use: '使用', vacuum: '真空', vehicle: '车辆', viscosity: '黏度',
  voyage: '航次', warehouse: '仓库', yellow: '黄色', yields: '可实现',
  active: '启用', actual: '实际', add: '新增', alignment: '对中', all: '全部', alarm: '报警',
  alert: '告警', alerts: '告警', analysis: '分析', analytics: '分析', angle: '角度', anomaly: '异常',
  archive: '档案', area: '区域', assessment: '评估', asset: '资产', assets: '资产', audit: '审计',
  auto: '自动', average: '平均', avg: '平均', balance: '平衡', baseline: '基准', bearing: '轴承',
  belt: '皮带', blade: '叶片', block: '区块', budget: '预算', bus: '母线', capacity: '容量',
  carbon: '碳排放', case: '案例', cases: '案例', cause: '原因', cavitation: '空化', center: '中心',
  chain: '链路', channel: '通道', check: '检查', checklist: '检查清单', class: '类别', cluster: '集群',
  code: '编码', command: '指令', compliance: '合规', component: '部件', confidence: '置信度',
  connection: '连接', consumption: '消耗', content: '内容', control: '控制', cooling: '冷却',
  correlation: '相关性', cost: '成本', crack: '裂纹', crane: '起重机', critical: '严重', current: '当前',
  curve: '曲线', cycle: '循环', cycles: '循环', cylinder: '油缸', damage: '损伤', dam: '大坝',
  data: '数据', database: '数据库', day: '天', days: '天', decision: '决策', defect: '缺陷',
  degradation: '劣化', density: '密度', depth: '深度', design: '设计', detected: '已检测', detection: '检测',
  deviation: '偏差', diagnosis: '诊断', diagnostics: '诊断', digital: '数字化', discharge: '排放',
  dispatch: '调度', distance: '距离', distribution: '分布', document: '文档', downtime: '停机时间',
  draft: '草稿', drill: '演练', drive: '驱动', due: '到期', dynamic: '动态', dynamics: '动力学',
  edge: '边缘', efficiency: '效率', energy: '能量', engine: '发动机', equipment: '设备', error: '错误',
  event: '事件', events: '事件', evolution: '演化', excellent: '优秀', execution: '执行', expert: '专家',
  factor: '因素', failure: '故障', fan: '风机', fatigue: '疲劳', feed: '给料', field: '场', filter: '筛选',
  fleet: '船队', flood: '洪水', flow: '流量', focus: '重点', forecast: '预测', force: '力',
  frequency: '频率', freq: '频率', friction: '摩擦', fuel: '燃料', full: '完整', gain: '增益', gas: '气体',
  gate: '闸门', gear: '齿轮', generator: '发电机', global: '全局', grade: '等级', grid: '电网',
  group: '组', guard: '防护', guide: '指南', head: '水头', health: '健康度', height: '高度', heavy: '重载',
  high: '高', history: '历史', hoist: '提升机', hours: '小时', hub: '枢纽', hull: '船体', hydraulic: '液压',
  hydraulics: '液压系统', impact: '冲击', index: '指数', inference: '推理', inflow: '入流', input: '输入',
  inspection: '巡检', insulation: '绝缘', integrity: '完整性', intensity: '强度', interactive: '交互式',
  internal: '内部', inventory: '库存', joint: '接头', key: '关键', knowledge: '知识', latency: '延迟',
  leakage: '泄漏', level: '等级', library: '知识库', life: '寿命', likelihood: '可能性', limit: '限值',
  line: '线路', link: '连接', live: '实时', load: '负载', log: '日志', logic: '逻辑', logistics: '物流',
  loss: '损失', low: '低', lubrication: '润滑', machinery: '机械', main: '主', management: '管理',
  manual: '手动', map: '地图', margin: '余量', marine: '船舶', material: '材料', matrix: '矩阵',
  maximum: '最大', max: '最大', mechanical: '机械', medium: '中等', metrics: '指标', mine: '矿山',
  mining: '矿山', minimum: '最小', mode: '模式', model: '模型', moderate: '中等', monitor: '监测',
  monitoring: '监测', months: '个月', motor: '电机', name: '名称', network: '网络', new: '新增',
  next: '下一步', node: '节点', nodes: '节点', normal: '正常', north: '北', now: '当前', offset: '偏移',
  oil: '油液', online: '在线', opening: '开度', operation: '运行', operational: '运行正常', operations: '运行',
  optimal: '最佳', optimization: '优化', optimized: '已优化', orbit: '轨迹', order: '工单', output: '输出',
  pad: '支承瓦', part: '部件', parts: '备件', pass: '通过', path: '路径', peak: '峰值', pending: '待处理',
  performance: '性能', phase: '相位', pipeline: '管线', pitch: '桨距', plan: '计划', points: '点位',
  port: '港口', potential: '潜在', power: '功率', precision: '精度', predicted: '预测', prediction: '预测',
  press: '压力', pressure: '压力', price: '价格', priority: '优先级', probability: '概率', process: '过程',
  production: '生产', profile: '画像', progress: '进度', projected: '预计', projection: '投影',
  protection: '保护', protocol: '协议', pump: '泵', quality: '质量', queue: '队列', radar: '雷达',
  rainfall: '降雨量', range: '范围', rate: '比率', ready: '就绪', reasoning: '推理',
  recommendation: '建议', recommended: '建议', recovery: '恢复', reduction: '减排', reliability: '可靠性',
  remaining: '剩余', replacement: '更换', report: '报告', req: '需求', required: '必需', reset: '重置',
  resistance: '阻力', resource: '资源', response: '响应', review: '评审', revenue: '收益', risk: '风险',
  rope: '钢丝绳', root: '根因', rotation: '旋转', run: '运行', running: '运行中', safe: '安全',
  safety: '安全', scan: '扫描', scanning: '扫描', schedule: '日程', score: '评分', search: '搜索',
  secure: '安全', security: '安全', selected: '已选择', selection: '选择', sensitivity: '灵敏度', sensor: '传感器',
  sensors: '传感器', sequence: '序列', service: '服务', session: '会话', set: '设置', shaft: '轴系',
  shield: '盾构机', shift: '班次', ship: '船舶', signal: '信号', signature: '特征', simulation: '仿真',
  simulator: '仿真器', site: '站点', skill: '技能', slot: '时段', smart: '智能', source: '来源',
  spare: '备件', spectrum: '频谱', speed: '速度', stability: '稳定性', stable: '稳定', standard: '标准',
  state: '状态', station: '站点', stats: '统计', status: '状态', step: '步骤', stock: '库存',
  strategy: '策略', stream: '数据流', stress: '应力', structural: '结构', structure: '结构', suggest: '建议',
  supply: '供应', support: '支护', surface: '表面', surge: '涌浪', sync: '同步', synced: '已同步',
  system: '系统', systems: '系统', task: '任务', team: '团队', tech: '技术', telemetry: '遥测',
  temperature: '温度', temp: '温度', tension: '张力', terminal: '终端', test: '测试', thermal: '热力',
  thickness: '厚度', threshold: '阈值', thrust: '推力', tide: '潮位', timeline: '时间线', time: '时间',
  today: '今天', tool: '工具', tools: '工具', top: '重点', topology: '拓扑', torque: '扭矩', total: '总计',
  tracking: '跟踪', training: '培训', trend: '趋势', trip: '跳闸', turbine: '水轮机', tuning: '调节',
  type: '类型', unit: '机组', units: '机组', value: '数值', valve: '阀门', verified: '已验证',
  velocity: '速度', vessel: '船舶', view: '视图', visual: '可视化', visualization: '可视化',
  vibration: '振动', vib: '振动', voltage: '电压', volume: '体积', warning: '预警', water: '水',
  wave: '波形', wear: '磨损', weibull: '威布尔', wind: '风', window: '窗口', within: '范围内',
  year: '年', years: '年', zone: '区域',
  above: '高于', and: '与', articles: '内容', at: '在', bandwidth: '带宽', based: '基于',
  below: '低于', by: '由', channels: '通道', continuous: '连续', corrosion: '腐蚀',
  designation: '名称', dropping: '下降', emergency: '紧急', exceeds: '超过', film: '油膜',
  for: '用于', found: '找到', from: '从', gap: '间隙', injection: '注入', in: '在',
  is: '为', lag: '滞后', length: '长度', liner: '衬套', matching: '匹配', no: '无',
  of: '的', on: '在', or: '或', outage: '停机', parameter: '参数', parameters: '参数',
  shutdown: '停机', specs: '规格', the: '', to: '至', transport: '运输', with: '与', your: '当前',

  ai: '人工智能', api: '应用接口', ar: '增强现实', agv: '自动导引车', ais: '船舶自动识别系统',
  bim: '建筑信息模型', bom: '物料清单', cad: '计算机辅助设计', cii: '碳强度指标',
  cms: '电缆管理系统', crm: '客户管理系统', doc: '文档', docx: '文档文件',
  eeoi: '船舶能效营运指数', erp: '企业资源管理系统', esg: '环境社会治理', excel: '电子表格',
  fmea: '故障模式与影响分析', fft: '快速傅里叶变换', gis: '地理信息系统', gim: '地理信息模型',
  html: '网页文档', id: '编号', igbt: '绝缘栅双极型晶体管', imo: '国际海事组织', iot: '物联网',
  iso: '国际标准', json: '数据交换格式', kpi: '关键绩效指标', loto: '挂牌上锁', markdown: '标记文档',
  mtbf: '平均故障间隔', mttr: '平均修复时间', ndt: '无损检测', oee: '设备综合效率',
  pdf: '便携文档', pid: '比例积分微分控制', plc: '可编程控制器', ptw: '作业许可',
  ram: '可靠性可用性可维护性', rms: '均方根', roi: '投资回报率', rul: '剩余寿命',
  scada: '监控与数据采集系统', sla: '服务等级协议', sop: '标准作业程序', sql: '数据库查询语言',
  teu: '标准箱', url: '链接', uv: '紫外线', vts: '船舶交通管理系统', web: '网页端', word: '文档',
  xls: '表格文件', xlsx: '表格文件', xml: '数据文件', jan: '一月', feb: '二月', mar: '三月',
  apr: '四月', may: '五月', jun: '六月', jul: '七月', aug: '八月', sep: '九月', oct: '十月',
  nov: '十一月', dec: '十二月', shanghai: '上海', singapore: '新加坡', rotterdam: '鹿特丹',
  china: '中国', starboard: '右舷', portside: '左舷', auxiliary: '辅助系统', propulsion: '推进系统',
  stator: '定子', rotor: '转子', runner: '转轮', governor: '调速器', impeller: '叶轮', nacelle: '机舱',
  gearbox: '齿轮箱', axial: '轴向', radial: '径向', vertical: '垂直方向', horizontal: '水平方向',
  upstream: '上游', downstream: '下游', encrypted: '已加密', wireless: '无线连接', realtime: '实时',
  optimum: '最佳', available: '可用', passed: '已通过', valid: '有效', details: '详情', criteria: '判据',
  patterns: '模式', waveform: '波形', heatmap: '热力图', standards: '标准',
  vs: '对比', twin: '孪生', factors: '因素', temporal: '时序', acoustic: '声学', acoustics: '声学',
  domain: '域', envelope: '包络', fault: '故障', fluctuation: '波动', select: '选择', decay: '衰减',
  diagnostic: '诊断', fingerprint: '特征指纹', allocation: '配置', assist: '辅助', condition: '工况',
  excitation: '激励', harmonic: '谐波', harmonics: '谐波', histogram: '直方图', kpis: '关键绩效指标',
  logs: '日志', lube: '润滑', mechanism: '机理', plot: '曲线图', predictive: '预测', prognostics: '趋势预测',
  propagation: '传播', qa: '质量保证', qc: '质量控制', registry: '登记信息', schematic: '原理图',
  section: '剖面', seismic: '地震', wheel: '车轮', accumulation: '累积', advisor: '智能建议',
  air: '空气', capability: '能力', chart: '图表', chemical: '化学', config: '配置', cumulative: '累计',
  displacement: '位移', drift: '漂移', eff: '效率', estimation: '估算', files: '文件', gateway: '网关',
  gauge: '仪表', governance: '治理', hammer: '锤击', hydrology: '水文', hysteresis: '滞回', idler: '托辊',
  ingestion: '数据接入', intelligent: '智能', ledger: '台账', loop: '回路', market: '市场', operating: '运行',
  orders: '工单', pareto: '帕累托', pd: '局部放电', polar: '极坐标', prognosis: '预测结论', prognostic: '预测',
  pulsation: '脉动', pulse: '脉冲', rail: '轨道', remote: '远程', scale: '尺度', servo: '伺服', summary: '摘要',
  tons: '吨', trajectory: '轨迹', transient: '瞬态', absorption: '吸收', access: '访问', actuator: '执行机构',
  adaptability: '适应性', adapters: '适配器', aerodynamics: '空气动力学', algo: '算法', algorithm: '算法',
  array: '阵列', arrhenius: '阿伦尼乌斯', assistant: '助手', attribution: '归因分析', aux: '辅助', ball: '球磨',
  base: '基础', battery: '电池', bending: '弯曲', benefit: '效益', binding: '绑定关系', boiler: '锅炉',
  bolt: '螺栓', calculator: '计算器', cascade: '级联', cash: '现金流', categories: '分类',
  certification: '认证', chamber: '腔室', charge: '装载量', chat: '会话', chemistry: '化学分析',
  classification: '分类', clustering: '聚类分析', cmd: '指令', collab: '协同', console: '控制台',
  contributors: '贡献因素', conversion: '转换', conveyor: '输送机', core: '核心', coupling: '联轴器',
  curves: '曲线', decisions: '决策', deformation: '变形', degrees: '角度', delta: '变化量', demand: '需求',
  depreciation: '折旧', detail: '详情', documents: '文档', downloads: '下载记录', drum: '卷筒',
  duane: '杜安', economic: '经济性', economics: '经济性分析', electrical: '电气', electromagnetic: '电磁',
  engagement: '参与度', entropy: '熵值', exhaust: '排气', feature: '特征', fender: '护舷', finance: '财务',
  fluid: '流体', forecasting: '预测', fouling: '污损', fracture: '断裂', frontier: '前沿', fusion: '融合',
  gallery: '廊道', genset: '发电机组', gnss: '卫星导航', gps: '卫星定位', graph: '关系图', growth: '增长',
  hotspots: '热点区域', hour: '小时', hse: '健康安全环境', hst: '液压机械传动', human: '人员',
  identity: '身份信息', imu: '惯性测量单元', ir: '红外', kb: '知识库', lab: '实验分析', last: '最近',
  loader: '装载机', manufacturing: '制造', mapping: '映射', metallurgy: '冶金', mitigation: '缓解措施',
  mix: '混合', modal: '模态', modes: '模式', nas: '网络存储', noise: '噪声', normalization: '归一化',
  nps: '净推荐值', opex: '运营成本', opt: '优化', physics: '物理机理', plumb: '垂线', point: '点位',
  propeller: '推进器', psd: '功率谱密度', pulley: '滚筒', ranking: '排序', rating: '评级', raw: '原始数据',
  readiness: '就绪度', recommendations: '建议措施', regulations: '法规要求', resolved: '已解决',
  resonance: '共振', ripple: '波动', roadmap: '实施路线', runout: '跳动量', sat: '卫星数据', scanner: '扫描仪',
  scatter: '散点图', segment: '分段', settings: '设置', settlement: '沉降', share: '占比', sim: '仿真',
  solar: '光伏', sources: '来源', spot: '现货', stack: '堆栈', strategies: '策略', suspension: '悬挂',
  swing: '摆动', syllabus: '培训大纲', tank: '储罐', target: '目标', teams: '团队', temperatures: '温度',
  theoretical: '理论值', tier: '层级', tire: '轮胎', transformer: '变压器', tree: '树状图', trolley: '小车',
  twistlock: '转锁', utilization: '利用率', validation: '验证', valuation: '价值评估', vault: '安全库',
  vectors: '向量', verdict: '研判结论', verification: '核验', version: '版本', wall: '壁面', wallet: '资金账户',
  weather: '气象', why: '原因分析', width: '宽度', wire: '钢丝', xrf: 'X射线荧光分析', ytd: '本年累计',
  zonal: '分区', acceleration: '加速度', accel: '加速度', accumulator: '蓄能器', accuracy: '准确率',
  actionable: '可执行建议', actions: '操作建议', adaptive: '自适应', advice: '建议', advisory: '建议',
  aeration: '曝气', after: '优化后', before: '优化前', aging: '老化', agreement: '协议', airflow: '风量',
  amplitude: '振幅', analyzer: '分析仪', annual: '年度', anomalies: '异常项', aperture: '孔径', arch: '拱部',
  archard: '阿查德', arcing: '电弧', assay: '化验', assignee: '负责人', assurance: '保障', atlas: '图谱',
  atomization: '雾化', attachments: '附件', authors: '编制人员', autonomous: '自主运行', bags: '滤袋',
  balancing: '平衡调整', barriers: '安全屏障', basic: '基础信息', bathtub: '浴盆曲线', bill: '清单',
  materials: '物料', items: '事项', lanes: '通道', tickets: '工单', internals: '内部机理',
  suggestion: '建议', suggestions: '建议', tactics: '处置策略', rules: '规则', reorder: '补货排序',
  services: '服务', dist: '分布', byproducts: '副产物', entrainment: '夹气',
  dominant: '主导成分', heat: '热状态', traffic: '流量', file: '文件',
  calibration: '标定', calibrated: '已标定', selector: '选择器', formulation: '配方',
  buildup: '积聚', breach: '溃口', berth: '泊位', berthing: '靠泊', bio: '生物', biometric: '生物识别',
  blockchain: '区块链', boom: '臂架', bow: '艏部', stern: '艉部', brake: '制动器', bucket: '斗轮',
  build: '构建版本', busbar: '母排', calculation: '计算', campaigns: '专项活动', candidates: '候选方案',
  capa: '纠正与预防措施', action: '处置', recommend: '建议', info: '信息', list: '清单',
  analyser: '分析仪', diag: '诊断', anti: '防', arc: '电弧', flash: '闪络',
  dna: '特征谱', policy: '策略', authorization: '授权', avionics: '航空电子设备', awards: '荣誉', cabinet: '档案柜',
  mill: '磨机', panto: '受电弓', gradient: '梯度', studies: '案例', study: '分析', custody: '保管',
  cell: '单元', certificate: '证书', certificates: '证书', cert: '认证', certs: '认证', chronology: '历程',
  circuit: '回路', circumferential: '周向', clearance: '间隙', closed: '闭环', match: '匹配', collaboration: '协同',
  combustion: '燃烧', common: '共性', compare: '对比', compatibility: '兼容性', completeness: '完整度',
  complexity: '复杂度', conflicts: '冲突', congestion: '拥堵', consensus: '共识', constellation: '星座',
  consumers: '使用方', contamination: '污染', contingency: '应急预案', contracts: '合同', contribution: '贡献度',
  controls: '控制项', conveyors: '输送设备', breakdown: '构成', eval: '评估', coupled: '耦合', coupon: '试片',
  cpa: '最接近点', credentials: '资质凭证', crest: '峰值', cross: '交叉', sell: '销售', crusher: '破碎机',
  crushing: '破碎', curated: '精选', tracks: '记录', currency: '币种', customize: '自定义', customs: '海关',
  cutter: '刀盘', cutting: '截割', cv: '计算机视觉', dataset: '数据集', datasheet: '数据表', dead: '呆滞',
  deliverables: '交付物', denoising: '降噪', dependencies: '依赖关系', designer: '设计人员', device: '设备',
  diagram: '示意图', dielectric: '介电', diesel: '柴油机', dimensions: '尺寸', direct: '直接', directional: '方向',
  directives: '指令', directory: '目录', discard: '废弃', dissipation: '散热', distillation: '蒸馏', diversity: '多样性',
  dosing: '加药', down: '下行', drain: '回油', dredger: '挖泥船', dredging: '疏浚', driller: '钻机',
  drills: '钻机', drivers: '诱因', drives: '驱动装置', duration: '持续时间', dust: '粉尘', early: '早期',
  earn: '挣值', burn: '消耗', redundancy: '冗余', emissions: '排放', emission: '排放', encryption: '加密',
  metabolism: '代谢', environment: '环境', equip: '设备', equity: '股权', estimated: '预计', execute: '执行',
  evidence: '证据', evolutionary: '演化', expiry: '到期', external: '外部', facility: '设施', feasibility: '可行性',
  ferrography: '铁谱分析', fidelity: '保真度', formats: '格式', financials: '财务指标', fishbone: '鱼骨图',
  flux: '通量', following: '跟随', formation: '地层', frame: '机架', gamification: '激励机制', gantry: '门机',
  gantt: '甘特图', gates: '闸门', genealogy: '谱系', generation: '发电', geometric: '几何', git: '版本库',
  gmf: '齿轮啮合频率', granularity: '粒度', green: '绿色', guidance: '指导建议',
  hardware: '硬件', historical: '历史', hourly: '每小时', hydrodynamic: '水动力', hydrodynamics: '水动力学',
  hydrostatic: '静水压力', hyperparameters: '超参数', hyperparams: '超参数', immutable: '不可篡改', importance: '重要度',
  indicator: '指标', indicators: '指标', industry: '行业', insights: '分析结论', intel: '情报', interactions: '交互关系',
  interdependency: '相互依赖', interference: '干扰', interval: '间隔', intervention: '干预', issues: '问题',
  iteration: '迭代', jaw: '颚板', kernel: '核心', kinetic: '动能', labeling: '标注', laser: '激光', law: '规律',
  layers: '分层', lead: '交付周期', learned: '经验总结', legacy: '存量', legal: '法务', lessons: '经验教训',
  lidar: '激光雷达', lifetime: '寿命', limits: '限值', linear: '线性', lissajous: '李萨如图', localized: '本地化',
  logarithmic: '对数', logbook: '运行记录', losses: '损失', magnetic: '磁性', manpower: '人力', mass: '质量',
  measures: '措施', mech: '力学', meshing: '啮合', metadata: '元数据', methodology: '方法体系',
  microseism: '微震', migration: '迁移', milestone: '里程碑', modeler: '建模工具', moisture: '含水率',
  multivariate: '多变量', navigation: '导航', negotiation: '协商', nominal: '额定', occupancy: '占用率',
  ontology: '本体', opportunities: '机会点', overview: '概览', ownership: '权属', persons: '人员',
  provenance: '数据来源', qualitative: '定性', quantitative: '定量', reconciliation: '核对',
  retention: '保留期限', scenario: '场景', scenarios: '场景', severity: '严重度', spectroscopy: '光谱分析',
  stakeholders: '相关方', symmetry: '对称性', trace: '追溯', uncertainty: '不确定性',
  uniformity: '均匀度', usability: '易用性', variance: '方差', vulnerabilities: '薄弱项', wide: '范围',
  analysis_result: '分析结果', benchmark_analysis: '对标分析', bin_analytics: '料仓分析',
  biometric_auth: '生物识别认证', blending: '配料混合', catalog: '目录', category_alert: '分类告警',
  category_select: '分类选择', catenary: '接触网', causal: '因果', cause_deconstruction: '原因拆解',
  conclusion: '分析结论', configuration: '配置管理', core_components: '核心部件',
  deduplication: '数据去重', distillation_form: '蒸馏记录表', domains: '业务域', dashboard: '看板',
  dlp: '数据防泄漏', dq: '数据质量', ecmv: '排放控制阀', eexi: '现有船舶能效指数',
  eho: '电子健康档案', electrochemical: '电化学', emergency_reserve: '应急储备', env: '环境',
  environment_sensing: '环境感知', etl: '数据抽取转换加载', evidence_locker: '证据库',
  evolution_track: '演化轨迹', expert_opinion: '专家意见', external_fees: '外部费用',
  feedback_input: '反馈录入', final_mile: '末端交付', fluid_genome: '流体特征谱',
  hpu: '液压动力单元', iam: '身份与访问管理', image: '图像', imaging: '成像', imdg: '国际海运危险货物规则',
  in_transit: '运输中', internal_tco: '内部总拥有成本', inventory_rank: '库存排序',
  investment_dna: '投资特征谱', isolation_matrix: '隔离矩阵', keys_status: '关键项状态',
  keyword_cloud: '关键词云', kpi_collision: '指标冲突', lifecycle: '全生命周期',
  lifecycle_analytics: '全生命周期分析', lifecycle_flux: '全生命周期变化', lifecycle_tag: '全生命周期标签',
  list_builder: '清单生成器', market_volatility: '市场波动', mechanics: '力学分析',
  metadata_extractor: '元数据提取', meteo: '气象', meters: '仪表', microns: '微米', millisecond: '毫秒级',
  miner: '采矿机', misalignment: '不对中', mode_concentration: '模态集中度', model_rank: '模型排序',
  modules: '模块', motion: '运动', motors: '电机', moves: '作业次数', nearby: '邻近',
  node_insight: '节点分析', obligations: '责任义务', offline: '线下', onsite: '现场', opinions: '意见',
  opportunity: '机会', optical: '光学', origin: '起点', out: '输出', outcome: '结果', outfall: '排放口',
  overall: '综合', overdue: '逾期', package: '程序包', packages: '程序包', packaging_audit: '包装审核',
  pain: '痛点', paper: '纸质', params: '参数', pareto_8020: '帕累托二八分析', particle: '颗粒', particles: '颗粒',
  partners: '合作伙伴', paths: '路径', pathway: '路径', pattern_dna: '模式特征谱', payment: '支付',
  penalty: '惩罚项', performers: '高绩效对象', permeability: '渗透率', permissives: '启动许可条件',
  personnel: '人员', physical: '物理', physicochemical: '理化指标', pier: '码头', plane: '平面',
  planetary: '行星级', planning: '计划', pneumatics: '气动系统', policies: '策略', pool: '水池', pools: '水池',
  portfolio: '组合', portfolio_analysis: '组合分析', positioning: '定位', powertrain: '动力传动系统',
  predict: '预测', preference: '偏好', prevention: '预防', processing: '处理', profit: '利润',
  projection_v2: '投影分析', propensity: '倾向度', proposals: '建议方案', provision_cart: '备件申领单',
  proximity: '邻近度', pumps: '泵组', qa_result: '质量检查结果', qcdst_audit: '质量成本交期安全审核',
  qty: '数量', quarantine: '隔离区', quay: '岸桥', quayside: '码头前沿', rainflow: '雨流', rank: '排序',
  rated: '额定', reality: '实际情况', recent: '近期', reclaiming: '取料', recon: '核对', records: '记录',
  regression: '回归', relations: '关联关系', repair_queue: '维修队列', reports: '报告', requisites: '前置条件',
  residual: '残差', residuals: '残差', result: '结果', rf_spectrum: '射频频谱', ring: '环',
  risk_hedging: '风险对冲', rock_hardness: '岩石硬度', rolling: '滚动', roster: '排班表', roughness: '粗糙度',
  routes: '路线', routing: '路由', sag: '弧垂', saving_engine: '节能分析引擎',
  saving_metrics: '节能指标', savings_model: '节能测算模型', scheduling: '排程', schema: '数据模式',
  scope: '范围', scoring_v2: '评分模型', scraping: '刮擦', screen: '筛分设备', sea: '海况',
  seal: '密封件', sealing: '密封', sealing_genius: '密封智能分析', seconds: '秒', sections: '分区',
  seismograph: '地震仪', sem: '结构方程模型', sem_visualization: '结构方程可视化',
  sensing_modes: '感知模式', sentiment: '舆情倾向', sentiment_timeline: '舆情趋势', sequencer: '顺序控制器',
  sfoc: '单位燃油消耗率', shm: '结构健康监测', shock: '冲击', shore: '岸侧', sieve: '筛网',
  sigma: '标准差', signs: '征兆', sla_intelligence: '服务等级智能分析', slewing: '回转', sliding: '滑动',
  slip: '滑移', slurry: '矿浆', snapshot: '快照', snr: '信噪比', social: '社会影响', soe: '事件顺序记录',
  solution: '解决方案', sonar: '声呐', spares: '备件', spatial: '空间', spatial_gains: '空间增益',
  spec_diff: '规格差异', spec_matrix: '规格矩阵', specification: '规格', spectral: '频谱', spectrogram: '频谱图',
  spectro_analysis: '光谱分析', spreader: '吊具', spring: '弹簧', stabilizers: '稳定器', stacker: '堆料机',
  stacking: '堆料', staff: '人员', stage: '阶段', startup_analysis: '启动分析', steam: '蒸汽',
  stochastic: '随机', stock_levels: '库存水平', stock_out: '缺货', storage: '存储', strain: '应变',
  strategic_path: '战略路径', strategic_reserve: '战略储备', stratigraphy: '地层分布', strength: '强度',
  stress_matirx: '应力矩阵', stressors: '应力源',
};

const SORTED_PHRASES = [...PHRASES].sort((a, b) => b[0].length - a[0].length);
const LOCALIZABLE_ATTRIBUTES = ['title', 'placeholder', 'aria-label', 'aria-description', 'alt'];
const SKIPPED_ELEMENTS = new Set(['SCRIPT', 'STYLE', 'NOSCRIPT', 'TEMPLATE']);
const TRANSLATABLE_STRUCTURED_LABELS = new Set(['auto-generated', 'auto-wear', 'real-time']);
const PRESERVED_TECHNICAL_ACRONYMS = new Set([
  'AGV', 'BAS', 'BEP', 'BIM', 'BOD5', 'CAD', 'CDR', 'CIP', 'COD', 'DGA', 'DFT', 'DO', 'EEBD',
  'EHS', 'EPB', 'ERP', 'ESR', 'FAT', 'FFT', 'FMEA', 'FTA', 'GIS', 'GNSS', 'GPS', 'HMI', 'IEC',
  'IGBT', 'IMO', 'ISO', 'KPI', 'LMI', 'LOTO', 'MFL', 'MLSS', 'MWD', 'NDT', 'NH3-N', 'NPSH', 'OCR', 'ORP', 'OSA', 'P&ID',
  'PCB', 'PD', 'PDR', 'PID', 'PLC', 'PMI', 'PPE', 'PSD', 'R', 'RFID', 'RMS', 'ROP', 'ROV', 'RUL', 'SAT',
  'SCADA', 'SLA', 'SLS', 'SOC', 'SOH', 'SOP', 'SS', 'SVI', 'SWL', 'TN', 'TP', 'UPS', 'UV', 'VFD',
  'VTS', 'XRF',
]);

interface PreparedCopy {
  text: string;
  restore: (value: string) => string;
}

function prepareCopyForTranslation(input: string): PreparedCopy {
  const protectedValues: string[] = [];
  const protect = (value: string): string => {
    const index = protectedValues.push(value) - 1;
    return `\uE000${index}\uE001`;
  };

  // 文件名及扩展名是可操作对象的真实标识，不能把 .pdf/.doc/.xls 等改成中文。
  let text = input
    .replace(/`[^`]+`/g, protect)
    .replace(/[^\s，。；：、（）()]+\.(?:csv|docx?|dwg|json|pdf|pptx?|txt|xlsx?|xml|zip)\b/gi, protect)
    .replace(/\.(?:csv|docx?|dwg|json|pdf|pptx?|txt|xlsx?|xml|zip)\b/gi, protect)
    // 菜单路由、场景 ID 和业务编码属于机器标识。即使它们嵌在中文说明中，
    // 也必须保持原值；普通英文类别和业务名称仍继续进入翻译流程。
    .replace(/\b(?:eq|kb|cp|ia|dd|sim|cdm|re|res|pm|am|sp|mm|km|sm|sh|ins|mpm|cv|vibe)-[A-Za-z0-9][A-Za-z0-9-]*\b/gi, protect)
    .replace(/\b(?=[A-Z0-9-]*\d)[A-Z]{2,}[A-Z0-9]*(?:-[A-Z0-9]+)+\b/g, protect);

  // 中文名称后附的普通英文释义会造成“调速器（调速器）”或“方位误差（轴承）”
  // 一类重复、错义。普通英文释义直接去除；行业通用缩写仍保留并阻止逐词改写。
  text = text.replace(/\s*[（(]\s*([A-Za-z][A-Za-z0-9+&/_. -]{0,60})\s*[）)]/g, (whole, gloss: string, offset: number, source: string) => {
    const before = source.slice(0, offset).trimEnd();
    if (!/[\u3400-\u9fff]$/.test(before)) return whole;
    const normalized = gloss.replace(/\s+/g, ' ').trim().toUpperCase();
    if (PRESERVED_TECHNICAL_ACRONYMS.has(normalized)) return protect(`（${normalized}）`);
    return '';
  });

  return {
    text,
    restore: (value: string) => value.replace(/\uE000(\d+)\uE001/g, (_whole, index: string) => protectedValues[Number(index)] ?? ''),
  };
}

function shouldPreserveElement(element: Element | null): boolean {
  if (!element) return false;
  return SKIPPED_ELEMENTS.has(element.tagName)
    || ['CODE', 'KBD', 'SAMP', 'PRE'].includes(element.tagName)
    || Boolean(element.closest('[data-localization="preserve"]'));
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function translateToken(token: string): string {
  const lower = token.toLowerCase();
  if (UNIT_TOKENS.has(lower)) return token;
  // 行业通用缩写是用户能够识别的专业标记，不应再被逐词展开；仅保留原本就是
  // 大写缩写的写法，避免把普通单词（如 individual）误判成缩写。
  if (token === token.toUpperCase() && PRESERVED_TECHNICAL_ACRONYMS.has(token.toUpperCase())) return token;
  const direct = WORDS[lower];
  if (direct) return direct;

  // 含数字的连字符/下划线组合通常是设备型号或业务编码，如 SHAFT-MAIN-01。
  if (/\d/.test(token) && /[-_]/.test(token)) return token;

  const parts = token.split(/[-_]+/).filter(Boolean);
  if (parts.length > 1) {
    const translatedParts = parts.map((part) => {
      const mapped = WORDS[part.toLowerCase()];
      if (mapped) return mapped;
      if (/^\d+(?:\.\d+)*$/.test(part)) return part;
      return null;
    });
    // 只有各段语义都明确时才组合翻译；设备型号、接口名和业务编码按原样保留。
    if (translatedParts.every((part): part is string => part !== null)) {
      return translatedParts.join('');
    }
    return token;
  }

  // 未收录的专有名称不再替换为“相关信息”或“标识”。这类文本通常是人名、
  // 品牌、型号或外部系统编码，保留原值比制造错误业务含义更符合中文习惯。
  return token;
}

function normalizeChineseCopy(input: string): string {
  return input
    .replace(/震动/g, '振动')
    .replace(/\b3D\b/gi, '三维')
    .replace(/\bAI\s*诊断\b/gi, '智能诊断')
    .replace(/实时振动分析与三维数字孪生/g, '振动实时分析与三维数字孪生')
    .replace(/振动频率分布/g, '振动频谱分布')
    .replace(/系统实时监测(.+?)振动监测的振动频谱分布/g, '系统实时分析$1的振动频谱')
    .replace(/系统实时监测(.+?)的振动频谱分布/g, '系统实时分析$1的振动频谱')
    .replace(/数据入库集成/g, '导入运行数据')
    .replace(/数据入库/g, '数据导入')
    .replace(/一键清空/g, '清空数据')
    .replace(/开始上传解析/g, '上传并解析')
    .replace(/正常运行中/g, '运行正常')
    .replace(/状态\s*:\s*/g, '状态：')
    .replace(/健康状态：优(?=$|[，。；\s])/g, '健康状态：优秀')
    .replace(/系统状态：优(?=$|[，。；\s])/g, '系统状态：优秀')
    .replace(/推进状态：活跃/g, '推进状态：运行中')
    .replace(/编号\s*:\s*/g, '编号：')
    .replace(/模式\s*:\s*/g, '模式：')
    .replace(/时间\s*:\s*/g, '时间：')
    .replace(/建议\s*:\s*/g, '建议：')
    .replace(/([\u3400-\u9fff])\s*:\s*/g, '$1：')
    .replace(/\s*\|\s*/g, ' ｜ ')
    .replace(/\s+([，。；：！？、）】])/g, '$1')
    .replace(/([（【])\s+/g, '$1')
    .replace(/([\u3400-\u9fff])\s+(?=[\u3400-\u9fff])/g, '$1')
    .replace(/([\u3400-\u9fff])\s+(?=[\u3400-\u9fff])/g, '$1')
    .replace(/[ \t]{2,}/g, ' ');
}

export function translateVisibleText(input: string): string {
  const trimmed = input.trim();
  const normalized = trimmed.toLowerCase();
  // 版本号、设备/字段代码和全大写结构化标签属于机器可读标识。它们可能同时
  // 被筛选、联动或导出逻辑使用，只翻译周边说明，不改写标识本身。
  const isMachineIdentifier = (
    /^v\d+(?:\.\d+)*(?:[-+][A-Za-z0-9.-]+)?$/i.test(trimmed)
    || /^(?=[A-Z0-9-]*\d)[A-Z][A-Z0-9]*(?:-[A-Z0-9]+)+$/.test(trimmed)
    || /^[A-Z0-9][A-Z0-9_&-]*_[A-Z0-9_&-]+$/.test(trimmed)
  );
  if (isMachineIdentifier && !TRANSLATABLE_STRUCTURED_LABELS.has(normalized)) {
    return input;
  }
  const exact = EXACT_TEXT[normalized];
  if (exact) {
    const leading = input.match(/^\s*/)?.[0] ?? '';
    const trailing = input.match(/\s*$/)?.[0] ?? '';
    return `${leading}${exact}${trailing}`;
  }

  const prepared = prepareCopyForTranslation(input);
  if (!/[A-Za-z]/.test(prepared.text)) return prepared.restore(normalizeChineseCopy(prepared.text));
  let result = prepared.text;
  for (const [english, chinese] of SORTED_PHRASES) {
    result = result.replace(new RegExp(`\\b${escapeRegExp(english)}\\b`, 'gi'), chinese);
  }
  return prepared.restore(normalizeChineseCopy(result
    .replace(/[A-Za-z][A-Za-z0-9_-]*/g, translateToken)
    .replace(/\s+([，。；：、])/g, '$1')
    .replace(/[ \t]{2,}/g, ' ')));
}

function localizeElementAttributes(element: Element): void {
  if (shouldPreserveElement(element)) return;
  for (const attribute of LOCALIZABLE_ATTRIBUTES) {
    const value = element.getAttribute(attribute);
    if (!value) continue;
    const translated = translateVisibleText(value);
    if (translated !== value) element.setAttribute(attribute, translated);
  }
  if (element instanceof HTMLInputElement && ['button', 'submit', 'reset'].includes(element.type)) {
    const translated = translateVisibleText(element.value);
    if (translated !== element.value) element.value = translated;
  }
}

function localizeNode(node: Node): void {
  if (node.nodeType === Node.TEXT_NODE) {
    const parent = node.parentElement;
    if (!parent || shouldPreserveElement(parent)) return;
    const value = node.nodeValue ?? '';
    const translated = translateVisibleText(value);
    if (translated !== value) node.nodeValue = translated;
    return;
  }
  if (!(node instanceof Element) && !(node instanceof ShadowRoot)) return;
  if (node instanceof Element) localizeElementAttributes(node);

  const walker = document.createTreeWalker(node, NodeFilter.SHOW_ELEMENT | NodeFilter.SHOW_TEXT);
  let current: Node | null = walker.nextNode();
  while (current) {
    if (current.nodeType === Node.TEXT_NODE) {
      const parent = current.parentElement;
      if (parent && !shouldPreserveElement(parent)) {
        const value = current.nodeValue ?? '';
        const translated = translateVisibleText(value);
        if (translated !== value) current.nodeValue = translated;
      }
    } else if (current instanceof Element) {
      localizeElementAttributes(current);
      if (current.shadowRoot) localizeNode(current.shadowRoot);
    }
    current = walker.nextNode();
  }
}

const canvasRoots = new Set<LocalizableRoot>();
let canvasPatchCount = 0;
let originalFillText: typeof CanvasRenderingContext2D.prototype.fillText | null = null;
let originalStrokeText: typeof CanvasRenderingContext2D.prototype.strokeText | null = null;

function canvasBelongsToLocalizedRoot(context: CanvasRenderingContext2D): boolean {
  return [...canvasRoots].some((root) => root instanceof HTMLElement && root.contains(context.canvas));
}

function enableCanvasLocalization(root: LocalizableRoot): () => void {
  canvasRoots.add(root);
  canvasPatchCount += 1;
  if (canvasPatchCount === 1) {
    originalFillText = CanvasRenderingContext2D.prototype.fillText;
    originalStrokeText = CanvasRenderingContext2D.prototype.strokeText;
    CanvasRenderingContext2D.prototype.fillText = function (text, x, y, maxWidth) {
      const visible = canvasBelongsToLocalizedRoot(this) ? translateVisibleText(String(text)) : String(text);
      return maxWidth === undefined
        ? originalFillText!.call(this, visible, x, y)
        : originalFillText!.call(this, visible, x, y, maxWidth);
    };
    CanvasRenderingContext2D.prototype.strokeText = function (text, x, y, maxWidth) {
      const visible = canvasBelongsToLocalizedRoot(this) ? translateVisibleText(String(text)) : String(text);
      return maxWidth === undefined
        ? originalStrokeText!.call(this, visible, x, y)
        : originalStrokeText!.call(this, visible, x, y, maxWidth);
    };
  }
  return () => {
    canvasRoots.delete(root);
    canvasPatchCount = Math.max(0, canvasPatchCount - 1);
    if (canvasPatchCount === 0 && originalFillText && originalStrokeText) {
      CanvasRenderingContext2D.prototype.fillText = originalFillText;
      CanvasRenderingContext2D.prototype.strokeText = originalStrokeText;
      originalFillText = null;
      originalStrokeText = null;
    }
  };
}

export function installChineseUiLocalization(
  root: LocalizableRoot,
  options: { localizeCanvas?: boolean } = {},
): () => void {
  localizeNode(root);
  const pending = new Set<Node>();
  let scheduled = false;
  const flush = () => {
    scheduled = false;
    const nodes = [...pending];
    pending.clear();
    nodes.forEach(localizeNode);
  };
  const observer = new MutationObserver((mutations) => {
    for (const mutation of mutations) {
      if (mutation.type === 'characterData') pending.add(mutation.target);
      mutation.addedNodes.forEach((node) => pending.add(node));
      if (mutation.type === 'attributes') pending.add(mutation.target);
    }
    if (!scheduled && pending.size) {
      scheduled = true;
      queueMicrotask(flush);
    }
  });
  observer.observe(root, {
    subtree: true,
    childList: true,
    characterData: true,
    attributes: true,
    attributeFilter: [...LOCALIZABLE_ATTRIBUTES, 'value'],
  });
  const disableCanvas = options.localizeCanvas ? enableCanvasLocalization(root) : () => undefined;
  return () => {
    observer.disconnect();
    pending.clear();
    disableCanvas();
  };
}
