/** Display-only vocabulary; raw IDs, protocol values and units remain unchanged. */
export const OPERATIONAL_CHINESE:Record<string,string>={
 'unit tests':'单元测试','due soon':'即将到期','sign off':'签字确认','win prob':'成交概率','param mismatch':'参数不匹配','vane pass':'叶片通过','est. uplift':'预计提升幅度','% prob':'% 概率','prob:':'概率：','prob':'概率','dev':'开发','crit':'严重','models':'模型','ships':'船舶','spots':'点位','elevated':'偏高','grease':'润滑脂','looseness':'松动','kurtosis':'峭度','overpressure':'超压',
 'tug':'拖轮','hangar':'机库','pause flow':'暂停交通流','resume flow':'恢复交通流','speed violations':'超速违规','near misses':'险情事件','inbound lane':'进港航道','outbound lane':'出港航道','restricted zone':'限制通行区域','vessel 413... entered restricted zone':'船舶413…进入限制通行区域','overspeed detected in channel a':'A航道检测到超速','low visibility warning issued':'已发布低能见度预警','sig. wave:':'有效波高：','view all incidents':'查看全部事件','traffic flow forecast (24h)':'交通流量预测（近24小时）','vts command center':'船舶交通管理指挥中心（VTS）','vts queue':'船舶交通管理队列','alerts today':'今日告警','volume':'流量','inbound (进港)':'进港','outbound (出港)':'出港',
 'huayun 05':'华运05号','huayun 88':'华运88号','changj iang':'长江号','chang jiang':'长江号','golden star':'金星号','blue whale':'蓝鲸号','river king':'江王号',
 'cosco star':'中远之星','msc gem':'地中海宝石号','ocean pride':'海洋骄傲号','harbor tug':'港作拖轮','dong fang 1':'东方1号','yuan yang':'远洋号','hai xun 01':'海巡01号','msc iris':'地中海鸢尾号','ever given':'长赐号','msc oscar':'地中海奥斯卡号','pacific gem':'太平洋宝石号','arctic wind':'北极风号','atlantic king':'大西洋之王号',
 'hydro-navigation system':'水运通航系统','chamber levels':'闸室水位','water cycle phase':'充泄水阶段','recycled':'循环利用','pump-back system active':'回水系统运行中','entry':'条目','exit':'退出','gate ops':'闸门操作','filling/emptying':'充水/泄水','filling/emptying is the critical path.':'充水/泄水是耗时控制的关键环节。',
 'med':'中等','mid':'中','syncing':'同步中','transit':'通行中','analyzing':'分析中','routine':'常规','expired':'已过期','software':'软件','extreme':'极端','checking':'检查中','doing':'进行中','busy':'忙碌','delivered':'已交付','amount':'数量','inspecting':'巡检中','blocked':'受阻','satellite':'卫星','occupied':'已占用','bulk':'散货船','anchored':'已锚泊','drifting':'漂航中','danger':'危险','calibrating':'校准中','moving':'移动中','return':'返回','turbidity':'浊度','reviewing':'审核中','audio':'音频','warn':'警告','drone':'无人机',
 'person':'个人','partner':'合作伙伴','compliant':'符合要求','churn':'流失','weakness':'薄弱项','mixed':'混合','delayed':'延迟','clean':'清洁','outbound':'出港','inbound':'进港','electronics':'电子设备','disch':'卸载','underway':'航行中','tanker':'油轮','patrol':'巡逻','patrolling':'巡逻中','biodiversity':'生物多样性','humidity':'湿度','fair':'良好','dry beach':'干滩','foggy':'有雾','haulage':'运输','congested':'拥堵','working':'作业中','rising':'上升','storm':'风暴','sprinklers':'喷淋装置','queued':'排队中','work':'作业','evacuate':'撤离','textiles':'纺织品','chemicals':'化学品','discharging':'卸载中','regulating':'调节中','reserve':'备用','steady':'平稳','cargo':'货船','fishing':'渔船','law enf':'执法船','overspeed':'超速','route dev':'航线偏离','anchoring':'锚泊','rescue helo':'救援直升机','sequestration':'固碳','species':'物种','sequestered':'已固存','calls':'呼叫','broadcast':'广播','chambers':'舱室','masks':'防护面罩','simulated':'模拟','staggered':'错列','entering':'进闸中','scheduled':'已安排','queue':'排队中',
 'eta:':'预计到达：','cap:':'容量：','exp:':'预计：','% conf.':'% 可信度','yrs':'年','util':'利用率','elev:':'高程：','travel pos:':'行走位置：','osmotic coefficient:':'渗透系数：','river level (ref)':'河道参考水位','search vessel by name or imo...':'按船名或 IMO 编号搜索…','sog speed':'对地航速','cargo composition':'货物构成','typhoon "khanun" nearby':'台风“卡努”临近','grade b+ (compliant)':'B+级（符合要求）','rtg cranes':'轮胎式集装箱门式起重机（RTG）','zero carbon initiative':'零碳行动','storage (ess)':'储能系统（ESS）','equalizing pressure...':'正在平衡压力…','smart agriculture water network':'智慧农业水网','total diversion':'总引水量','branch canal':'支渠','salinity (ec)':'盐度（EC）','grid side':'电网侧','maritime safety administration (msa)':'海事管理机构（MSA）','radar coverage':'雷达覆盖范围','spd:':'速度：','reclaimed area':'复垦面积','virtual eco-park twin':'生态园区数字孪生','soil improvement':'土壤改良','water treatment':'水处理','waste recycling':'废弃物回收','time since incident':'事件已持续时间','awaiting transmission...':'等待传输…','ventilation booster':'通风增压机','underground comms':'井下通信','pool lvl':'水池液位','underground safety guardian':'井下安全防护','shift leader':'值班负责人','net power':'净功率','reversible turbine:':'可逆式水轮机：','recycle capacity':'循环处理能力','old town s':'老城区南区','resid. west':'西部住宅区','urban water intelligence':'城市智慧水务','nrw rate':'无收益水率（NRW）','gis nodes':'地理信息节点（GIS）','onl':'在线','motor cur:':'电机电流：','holographic stator & winding thermal field digital twin':'定子与绕组温度场数字孪生','high turbidity indicates internal erosion (piping).':'高浊度提示可能存在内部侵蚀（管涌）。','deform':'变形','bor (occupancy)':'泊位占用率（BOR）','orange: blast hole':'橙色：炮孔','red: shockwave':'红色：冲击波','grey: muckpile':'灰色：爆堆',
 'cargo a':'A号货船','cargo d':'D号货船','tanker b':'B号油轮','barge c':'C号驳船','iron ore a':'A类铁矿石','iron ore b':'B类铁矿石','ore a':'A类矿石','ore b':'B类矿石','automated terminal operating system (tos)':'自动化码头操作系统（TOS）',
};

export const OPERATIONAL_WORDS:Record<string,string>={
 publish:'发布',retired:'已退役',installation:'安装',validity:'有效性',consistency:'一致性',reject:'拒绝',flagged:'已标记',finished:'已完成',corrective:'纠正性',extended:'已延长',listening:'监听中',context:'上下文',text:'文本',param:'参数',soon:'即将到来',intermediate:'中间',deviate:'偏离',reactive:'响应式',subsystem:'子系统',probable:'可能',consumer:'使用方',suspected:'疑似',excluded:'已排除',mitigated:'已缓解',approval:'审批',acceptable:'可接受',investigating:'调查中',optimizing:'优化中',fuzzy:'模糊',uplift:'提升幅度',holistic:'综合',electronic:'电子',matched:'已匹配',missing:'缺失',node:'节点',collision:'碰撞',vortex:'涡流',sampling:'采样',disassembly:'拆解',synthesis:'合成',vision:'视觉',steering:'转向',compressor:'压缩机',coil:'线圈',hybrid:'混合',bushing:'衬套',immediately:'立即',uplink:'上行链路',setpoint:'设定值',scour:'冲刷',subterranean:'地下',mast:'桅杆',tests:'测试',shipping:'航运',tomorrow:'明天',users:'用户',invest:'投资',director:'主管',executive:'负责人',registered:'已登记',capital:'资本',more:'更多',period:'周期',agent:'代理',auth:'认证',free:'免费',pricing:'定价',procurement:'采购',communication:'通信',rights:'权益',competitor:'竞争对手',reach:'达到',role:'角色',conflict:'冲突',influence:'影响',neutral:'中性',signals:'信号',purchased:'已购买',trade:'交易',billing:'账单',firmware:'固件',deposit:'保证金',confirmed:'已确认',calc:'计算',east:'东部',webinar:'线上研讨会',sessions:'会话',configure:'配置',scrap:'报废',related:'相关',risky:'高风险',positive:'正向',planned:'计划内',workshop:'车间',finalize:'完成确认',deadline:'截止时间',subject:'主题',bridge:'桥梁',weak:'薄弱',axis:'轴线',complete:'完成',tower:'塔架',fire:'火灾',recognition:'识别',smoke:'烟雾',terrain:'地形',rack:'机架',powerhouse:'厂房',coating:'涂层',diff:'差异',constraints:'约束条件',excavation:'开挖',packet:'数据包',surveillance:'监控',commissioning:'调试',mooring:'系泊',conditions:'工况',risks:'风险',rejection:'拒收',circular:'循环',reconstruction:'重建',longitudinal:'纵向',samples:'样本',drag:'阻力',hardness:'硬度',semantic:'语义',setting:'设置',relative:'相对',release:'发布',broken:'损坏',front:'前部',fastener:'紧固件',workbench:'工作台',overhaul:'大修',reached:'已达到',collaborative:'协同',trainee:'学员',toggle:'切换',economy:'经济性',results:'结果',explosion:'爆炸',inverter:'逆变器',synchronization:'同步',predictor:'预测器',closing:'关闭中',plunger:'柱塞',saving:'节约量',shape:'形状',significant:'显著',slider:'滑块',trunnion:'耳轴',furfural:'糠醛',bottom:'底部',rapid:'快速',insulator:'绝缘子',degraded:'性能下降',effective:'有效',damping:'阻尼',retrofit:'改造',induced:'诱发',
 technical:'技术',neural:'神经网络',winding:'绕组',contact:'联系',unbalance:'不平衡',connected:'已连接',coverage:'覆盖范围',ore:'矿石',integration:'集成',upgrade:'升级',visit:'访问',product:'产品',comms:'通信',layer:'层',partial:'局部',stroke:'行程',maritime:'海事',troubleshooting:'故障排查',weight:'重量',rotating:'旋转',hydro:'水力',mismatch:'不匹配',piston:'活塞',user:'用户',statement:'声明',adjustment:'调整',verify:'验证',survey:'调查',plate:'板件',learning:'学习',tunnel:'隧道',pipe:'管道',vector:'矢量',weld:'焊缝',instability:'不稳定',pneumatic:'气动',beach:'滩面',housing:'壳体',month:'月',upcoming:'即将到来',business:'业务',ago:'之前',ask:'提问',submit:'提交',insight:'分析见解',identified:'已识别',guardian:'防护',position:'位置',silt:'淤积物',sets:'组',dissolved:'溶解',rock:'岩石',regulatory:'监管',overload:'过载',scene:'场景',switch:'切换',roller:'辊轮',carrier:'载体',original:'原始',spec:'规格',interaction:'交互',question:'问题',supplier:'供应商',launch:'启动',preview:'预览',signed:'已签署',discount:'折扣',sales:'销售',framework:'框架',updated:'已更新',custom:'定制',tag:'标签',mins:'分钟',completion:'完成情况',location:'位置',behavior:'行为',region:'区域',manage:'管理',create:'创建',west:'西部',reverse:'反向',serial:'序列',handling:'处理',special:'专项',linked:'已关联',certified:'已认证',bid:'投标',trial:'试用',vendor:'供应商',iron:'铁',travel:'行走',coefficient:'系数',approaching:'正在接近',identification:'识别',worn:'磨损',payload:'载荷',restricted:'受限',visibility:'能见度',issued:'已发布',entered:'已进入',lane:'航道',violations:'违规',pending:'待处理',approved:'已批准',rejected:'已拒绝',resolved:'已解决',assigned:'已分配',completed:'已完成',cancelled:'已取消',offline:'离线',online:'在线',paused:'已暂停',resume:'恢复',pause:'暂停',disconnected:'已断开',reconnecting:'重新连接中',failed:'失败',success:'成功',warning:'预警',normal:'正常',abnormal:'异常',enabled:'已启用',disabled:'已禁用',draft:'草稿',archived:'已归档',queued:'排队中',idle:'空闲',running:'运行中',stopped:'已停止',loading:'加载中',processing:'处理中',waiting:'等待中',ready:'就绪',locked:'已锁定',unlocked:'已解锁',available:'可用',unavailable:'不可用',
};
